#!/bin/bash

say -v Kyoko "	私に考えが浮かんだ	"; say -v Karen "	It occurred to me	"
say -v Kyoko "	彼が何かを隠していたという考えが．	"; say -v Karen "	that he was holding something back,	"
say -v Kyoko "	なぜなら彼が私の目を見ようとしなかったので	"; say -v Karen "	because he couldn't look me in the eye.	"
say -v Kyoko "	彼女の忍耐が尽きた時，	"; say -v Karen "	When her patience gave out,	"
say -v Kyoko "	彼女は彼の襟を掴んで彼を罵った	"; say -v Karen "	she grabbed his collar and swore at him.	"
say -v Kyoko "	私は認めなければならない、私たちが口喧嘩することを、たまに，	"; say -v Karen "	I must admit we quarrel every now and then,	"
say -v Kyoko "	しかし普通は	"; say -v Karen "	but generally	"
say -v Kyoko "	私たちは仲が良い、お互い	"; say -v Karen "	we're on good terms with each other.	"
say -v Kyoko "	君の家に寄ってもいいですか？	"; say -v Karen "	Do you mind if I stop by your house?	"
say -v Kyoko "	いや全然．遠慮しないで	"; say -v Karen "	No, not at all. Be my guest.	"
say -v Kyoko "	ちょっと待ってて．私はすぐに戻ってくるよ．	"; say -v Karen "	Hold on. I'll be right back. 	"
say -v Kyoko "	切らないで	"; say -v Karen "	Don't hang up.	"
say -v Kyoko "	私はあなたを泊められない．	"; say -v Karen "	I can't put you up. 	"
say -v Kyoko "	一つには，父がふらっと立ち寄るから	"; say -v Karen "	For one thing, my dad drops in on me	"
say -v Kyoko "	時々	"; say -v Karen "	from time to time.	"
say -v Kyoko "	ジェニファーがじっと立っている時	"; say -v Karen "	While Jennifer was standing still,	"
say -v Kyoko "	ボブは歩いていた、行ったり来たり、歩道を	"; say -v Karen "	Bob was pacing back and forth along the sidewalk.	"
say -v Kyoko "	仲直りしよう，リサ．	"; say -v Karen "	Let's make up, Lisa. 	"
say -v Kyoko "	私がいて当然のことと思わないで．	"; say -v Karen "	Stop taking me for granted. 	"
say -v Kyoko "	私たちは終わりです、永遠に、今度は．	"; say -v Karen "	We're through for good this time. 	"
say -v Kyoko "	本気で言っているんだよ	"; say -v Karen "	I mean it.	"
say -v Kyoko "	おいおい．感情的になるな，リサ．	"; say -v Karen "	Come on. Don't get so emotional, Lisa. 	"
say -v Kyoko "	私はあなたを傷つけるつもりではなかった．	"; say -v Karen "	I didn't mean to hurt you. 	"
say -v Kyoko "	それについてよく話し合おう	"; say -v Karen "	Let's talk it over.	"
say -v Kyoko "	あなたは私を裏切った．	"; say -v Karen "	You betrayed me. 	"
say -v Kyoko "	許してください．	"; say -v Karen "	Please forgive me. 	"
say -v Kyoko "	どのように私は埋め合わせできますか．	"; say -v Karen "	How can I make it up to you? 	"
say -v Kyoko "	私は仕返しします	"; say -v Karen "	I'll get even.	"
say -v Kyoko "	あなたは告白するべきだ、あなたの罪を	"; say -v Karen "	You should confess your sins	"
say -v Kyoko "	それらを隠すよりは	"; say -v Karen "	rather than conceal them.	"
say -v Kyoko "	あなたの約束を守りなさい．	"; say -v Karen "	Keep your word; 	"
say -v Kyoko "	そうしなければ，あなたは評判を落とす結果になります	"; say -v Karen "	otherwise you'll end up/losing face.	"
say -v Kyoko "	ボブは守る、彼の道徳的な信条を	"; say -v Karen "	Bob sticks to his moral principles	"
say -v Kyoko "	そして信じている、正直は報われる、最後には	"; say -v Karen "	and believes that honesty pays off in the long run.	"
say -v Kyoko "	元気を出して．それは仕方がなかった．私はベストを尽くした．	"; say -v Karen "	Cheer up! You couldn't help it. I did my best. 	"
say -v Kyoko "	わかってる．くよくよしないで、過去に．あなたはやり直せる．	"; say -v Karen "	I know. Don't dwell on the past. You can start over.	"