#!/bin/bash

say -v Kyoko "	僕には理解できない	"; say -v Karen "	I cant' figure out	"
say -v Kyoko "	なぜそんなにみんながボブのことを軽蔑するのか	"; say -v Karen "	why on earth everybody feels so much contempt for Bob.	"
say -v Kyoko "	私は笑わずにはいられなかった、彼を	"; say -v Karen "	I can't help laughing at him	"
say -v Kyoko "	なぜなら彼がし続けるから、馬鹿な間違いを．	"; say -v Karen "	because he keeps on making stupid mistakes. 	"
say -v Kyoko "	彼は最も可能性の低い人だ、懲りる	"; say -v Karen "	He'd be the last person to learn his lesson.	"
say -v Kyoko "	さらに悪いことに	"; say -v Karen "	To make matters worse,	"
say -v Kyoko "	彼は自覚さえしていない	"; say -v Karen "	he isn't even conscious of	"
say -v Kyoko "	私たちを不快な気分にしていることを	"; say -v Karen "	annoying us.	"
say -v Kyoko "	私は慌てていたので，	"; say -v Karen "	Since I was in a hurry,	"
say -v Kyoko "	私は手袋をはめた、裏返しに、間違って	"; say -v Karen "	I put my gloves inside out by mistake.	"
say -v Kyoko "	デイブは太っていて不器用．	"; say -v Karen "	Dave is fat and clumsy. 	"
say -v Kyoko "	彼が飛び越えた時、浅い小川を	"; say -v Karen "	When he leaped over the shallow stream,	"
say -v Kyoko "	彼は躓いて足首を捻挫した	"; say -v Karen "	he stumbled and twisted his ankle.	"
say -v Kyoko "	私は怖い、高いところが．	"; say -v Karen "	I'm scared of heights. 	"
say -v Kyoko "	あなたは臆病者です	"; say -v Karen "	You're a coward.	"
say -v Kyoko "	消極的な男性はめったにしない	"; say -v Karen "	The passive man seldom, if ever,	"
say -v Kyoko "	自分を表現することを、人前で	"; say -v Karen "	express himself in public.	"
say -v Kyoko "	ニックは私を納得させた	"; say -v Karen "	Nick convinced me	"
say -v Kyoko "	すべての迷信は根拠がない	"; say -v Karen "	that all superstitions are irrational.	"
say -v Kyoko "	私は震える、恐怖で	"; say -v Karen "	I tremble with fear	"
say -v Kyoko "	注射のことを考えると	"; say -v Karen "	at the thought of an injection.	"
say -v Kyoko "	ボブは怠惰なので、心の底では	"; say -v Karen "	Since Bob is lazy at heart,	"
say -v Kyoko "	彼は頻繁に怠る、彼の義務を	"; say -v Karen "	he frequently neglects/his duty.	"
say -v Kyoko "	ボブが働いている間，	"; say -v Karen "	While Bob was at work,	"
say -v Kyoko "	ジェニファーは家で夢中になっていた	"; say -v Karen "	Jennifer was at home absorbed	"
say -v Kyoko "	馬鹿なメロドラマに	"; say -v Karen "	in silly soap operas.	"
say -v Kyoko "	ボブは漫画が好きだ	"; say -v Karen "	Bob likes cartoons,	"
say -v Kyoko "	しかし私はそれらを高く評価しない．	"; say -v Karen "	but I don't think much of them. 	"
say -v Kyoko "	実際にはそれらは退屈だ．	"; say -v Karen "	As a matter of fact, they're boring.	"