#!/bin/bash

say -v Kyoko "	片付けなさいここにあるものを．	"; say -v Karen "	Put this stuff away! 	"
say -v Kyoko "	それはじゃまになっている	"; say -v Karen "	It's in the way.	"
say -v Kyoko "	子どもたちが真似をして遊んでいるとき、彼らが恐竜である	"; say -v Karen "	When the kids made believe they were dinosaurs,	"
say -v Kyoko "	彼らは叱られた、彼らの母に	"; say -v Karen "	they were scolded by their mother.	"
say -v Kyoko "	彼がぶつかったあとに、棚に	"; say -v Karen "	After he bumped into the shelf,	"
say -v Kyoko "	高価な陶磁器が落ちた	"; say -v Karen "	the priceless china fell 	"
say -v Kyoko "	そして粉々になった	"; say -v Karen "	and shattered into fragments.	"
say -v Kyoko "	あなたはうちの子供達から目を離さないでもらえますか、しばらく．	"; say -v Karen "	Can you keep an eye on my kids for a while.	"
say -v Kyoko "	私は必要がある、ケンを迎えに行く．	"; say -v Karen "	 I need to pick up Ken. 	"
say -v Kyoko "	問題ない	"; say -v Karen "	No problem.	"
say -v Kyoko "	隣人が私たちに説教した	"; say -v Karen "	One neighbor told us off	"
say -v Kyoko "	めちゃくちゃにされたことを、庭を	"; say -v Karen "	 for making a mess in his yard.	"
say -v Kyoko "	ドリーはお姉さんに似ている、あらゆる点で	"; say -v Karen "	Dolly resembles her big sister in every way. 	"
say -v Kyoko "	あなたは二人を区別できない	"; say -v Karen "	You can't tell them apart.	"
say -v Kyoko "	概して、双子は共通点が多い	"; say -v Karen "	As a rule, twins have a lot in common.	"
say -v Kyoko "	私はうんざりしている	"; say -v Karen "	I'm tired of 	"
say -v Kyoko "	皿洗いとか，洗濯とかそういうことに	"; say -v Karen "	doing the dishes, doing the laundry, and so on!	"
say -v Kyoko "	私のお気に入りの楽しみはブラブラと歩くことです、浜辺を．	"; say -v Karen "	My favorite pastime is strolling along the shore.	"
say -v Kyoko "	それは楽しい	"; say -v Karen "	 It's pleasant.	"
say -v Kyoko "	私，もうクタクタ．休憩しよう、日陰で．	"; say -v Karen "	I'm exhausted! Let's take a break in the shade. 	"
say -v Kyoko "	そうだね	"; say -v Karen "	Why not?	"
say -v Kyoko "	ボブ，この自動販売機，故障してるわ．	"; say -v Karen "	Bob, this vending machine is out of order. 	"
say -v Kyoko "	なんだって．私は死にそうです、のどが渇いて	"; say -v Karen "	Oh, no. I'm dying of thirst.	"
say -v Kyoko "	彼は気を失った、空腹と疲労で	"; say -v Karen "	He fainted with hunger and fatigue,	"
say -v Kyoko "	しかし意識を回復した、しばらくして	"; say -v Karen "	 but came to after a while.	"