#!/bin/bash

say -v Kyoko "	私たちは背を向けることができない	"; say -v Karen "	We cannot turn our backs 	"
say -v Kyoko "	絶望した人々に、危険にさらされている	"; say -v Karen "	on desperate people who are at risk.	"
say -v Kyoko "	議会は決めた、提供することを	"; say -v Karen "	The parliament decided to provide 	"
say -v Kyoko "	発展途上国に、財政援助を	"; say -v Karen "	developing countries with financial aid.	"
say -v Kyoko "	言う人がいる、英国の君主制は廃止されるべきだと．	"; say -v Karen "	Some say the British monarchy should be abolished.	"
say -v Kyoko "	あなたはどう思う？	"; say -v Karen "	What do you think?	"
say -v Kyoko "	彼らは安全な場所を探した、攻撃から	"; say -v Karen "	They sought shelter from the attack 	"
say -v Kyoko "	しかし場所は見つからなかった、隠れるための	"; say -v Karen "	but found no place to hide.	"
say -v Kyoko "	可能性はほとんどない	"; say -v Karen "	There's little prospect	"
say -v Kyoko "	２つの国が大きな進展をする、軍備縮小において	"; say -v Karen "	that the two countries will make significant progress in disarmament.	"
say -v Kyoko "	交渉は進行中である．	"; say -v Karen "	The negotiations are under way. 	"
say -v Kyoko "	間もなく、彼らは入るだろう、極めて重大な局面に	"; say -v Karen "	Before long, they will enter a crucial phase.	"
say -v Kyoko "	奴隷たちは切望していた、彼らの運命を変えることを	"; say -v Karen "	The slaves were anxious to alter their destinies.	"
say -v Kyoko "	貴族たちは乱用した、彼らの特権を	"; say -v Karen "	The aristocrats abused their privileges	"
say -v Kyoko "	彼らの思う存分に	"; say -v Karen "	to their hearts' content.	"
say -v Kyoko "	革命それ自体はもたらさなかった、なんの成果も	"; say -v Karen "	The revolution in itself, bore no fruit,	"
say -v Kyoko "	結局．	"; say -v Karen "	after all.	"