#!/bin/bash

say -v Kyoko "	直美は見せびらかすのが好きだ	"; say -v Karen "	Naomi likes to show off/	"
say -v Kyoko "	彼女の完璧なスタイルを．	"; say -v Karen "	her perfect figure. 	"
say -v Kyoko "	私も痩せていたらなあ、彼女のように．	"; say -v Karen "	I wish I were thin like her. Y	"
say -v Kyoko "	君はダイエットできる	"; say -v Karen "	ou could go no a diet.	"
say -v Kyoko "	私はナオミに恋をした、ひと目見ただけで．	"; say -v Karen "	I fell in love Naomi at first sight. 	"
say -v Kyoko "	3ヶ月後，私は思い切って彼女にプロポーズした，	"; say -v Karen "	Three months later, I took chance and proposed her, 	"
say -v Kyoko "	しかし彼女は私を断った	"; say -v Karen "	but she turned me down.	"
say -v Kyoko "	私はその男に会った、偶然に．	"; say -v Karen "	I met the man by chance. 	"
say -v Kyoko "	彼は優しくて頭が良かった．	"; say -v Karen "	He's gentle and smart. 	"
say -v Kyoko "	おまけに，彼は独身だ	"; say -v Karen "	What's more, he's single.	"
say -v Kyoko "	彼の甥は育てられた	"; say -v Karen "	His nephew was brought up 	"
say -v Kyoko "	謙虚で思いやりのあるように	"; say -v Karen "	to be modest and considerate.	"
say -v Kyoko "	私はボブを両親に紹介した，	"; say -v Karen "	I introduced Bob to my folks, 	"
say -v Kyoko "	そして彼らは彼を好きになった、すぐに	"; say -v Karen "	and they took to him at once.	"
say -v Kyoko "	人々は判断されるべきだ	"; say -v Karen "	People should be judged	"
say -v Kyoko "	外見というよりはむしろ中身で	"; say -v Karen "	not so much by how they look as by who they are.	"
say -v Kyoko "	肩書こそが重要なのではない．	"; say -v Karen "	It's not your title that counts. 	"
say -v Kyoko "	それは確かだ．語気を強めて言った，ボブが	"; say -v Karen "	That's for sure. Exclaimed Bob.	"
say -v Kyoko "	自分の努力で成功した人が言ったように	"; say -v Karen "	As a self-made man put it,	"
say -v Kyoko "	先見の明がある人は成功する，最後に	"; say -v Karen "	A man of vision will make good in the end	"
say -v Kyoko "	覚えておきなさい	"; say -v Karen "	Keep in mind	"
say -v Kyoko "	若さが永遠ではないことを	"; say -v Karen "	that youth is not eternal.	"