#!/bin/bash

say -v Kyoko "	ジェーン，お願いがあるんだけど	"; say -v Karen "	Jane, please do me a favor	"
say -v Kyoko "	そして私を載せてってください、タイムズスクエアまで．	"; say -v Karen "	and give me a ride to Times Square. 	"
say -v Kyoko "	できればよかったけど、しかし私は今とても忙しい	"; say -v Karen "	I wish I could, but I'm tied up right now.	"
say -v Kyoko "	いつも通り、マイクは現れた、時間通りに．	"; say -v Karen "	As usual, Mike turned up on time. 	"
say -v Kyoko "	彼はとても時間を厳守する	"; say -v Karen "	He's very punctual.	"
say -v Kyoko "	この前	"; say -v Karen "	The other day	"
say -v Kyoko "	私はガソリンを使い果たした、真ん中で、混雑した幹線道路の	"; say -v Karen "	I ran out of gas in the middle of a busy interstate.	"
say -v Kyoko "	トラックが私の前を走っていた	"; say -v Karen "	A truck driving ahead of me	"
say -v Kyoko "	スリップして転倒し、そして積荷をばらまいた	"; say -v Karen "	skidded, turned over, and scattered its load	"
say -v Kyoko "	道路いっぱいに	"; say -v Karen "	all over the road.	"
say -v Kyoko "	彼は思い出した、衝突は避けられたことを	"; say -v Karen "	He recalled that a collision had been avoided	"
say -v Kyoko "	全くの幸運で	"; say -v Karen "	by sheer luck.	"
say -v Kyoko "	緊急の場合には	"; say -v Karen "	In case of emergency,	"
say -v Kyoko "	連絡を取ってください、代理人と、すぐに	"; say -v Karen "	get in touch with my agent right away.	"
say -v Kyoko "	ジェーン，私達はどこに向かっていますか？	"; say -v Karen "	Jane, where are we heading? 	"
say -v Kyoko "	迷ったと思う．私たちは間違った方向に来た．	"; say -v Karen "	I think we're lost. We went in the wrong direction. 	"
say -v Kyoko "	なんだって．車を止めてくれ	"; say -v Karen "	Damn. Pull over.	"
say -v Kyoko "	私の錆びついたフォードが故障して、交差点を塞いだ	"; say -v Karen "	My rusty Ford broke down, obstructing the intersection.	"
say -v Kyoko "	とてもたくさんの細かい引っかき傷とへこみがある、表面に，	"; say -v Karen "	There are so many fine scratches and dents on its surface,	"
say -v Kyoko "	それを磨いても無駄だ	"; say -v Karen "	it's no use polishing it.	"
say -v Kyoko "	おい，私たちははまっている、渋滞に．	"; say -v Karen "	Hey, we're stuck in a traffic jam. 	"
say -v Kyoko "	冷静になって，ジョー．近道しよう．	"; say -v Karen "	Chill out, Joe. Let's take a shortcut. 	"
say -v Kyoko "	私たちは着ける、時間通りに	"; say -v Karen "	We'll get there in time.	"
say -v Kyoko "	私はタイヤがパンクした．	"; say -v Karen "	I've got a flat tire. 	"
say -v Kyoko "	あなたは私を手助けしてくれませんか．	"; say -v Karen "	Can you give me a hand?	"
say -v Kyoko "	ええ，喜んで	"; say -v Karen "	 I'd be glad to.	"
say -v Kyoko "	救急車は制御を失った	"; say -v Karen "	The ambulance went out of control	"
say -v Kyoko "	そして危うく轢きそうになった、歩行者を	"; say -v Karen "	and came close to running over a pedestrian.	"