#!/bin/bash

say -v Kyoko "	あなたの課題を提出してください、メールで	"; say -v Karen "	Please hand in your assignment via e-mail	"
say -v Kyoko "	午後５時までに、６月１０日の	"; say -v Karen "	no later than 5:00 PM on June 10.	"
say -v Kyoko "	ジョーが勤勉とは思えない．	"; say -v Karen "	Joe is anything but diligent. 	"
say -v Kyoko "	そういうわけで彼は数学を落とした、再度	"; say -v Karen "	That's why he flunked math again.	"
say -v Kyoko "	彼の論文は意味をなしていない．	"; say -v Karen "	his thesis doesn't make sense. 	"
say -v Kyoko "	まず第一に，その主題は曖昧だ	"; say -v Karen "	To begin with, its theme is obscure.	"
say -v Kyoko "	彼のエッセイは簡潔で要領を得ていた	"; say -v Karen "	His essay was concise and to the point.	"
say -v Kyoko "	あなたはどのように処理するつもりですか、この複雑な問題を．	"; say -v Karen "	How are you going to deal with this complicated problem? 	"
say -v Kyoko "	それは私に任せろ．朝飯前だ	"; say -v Karen "	Leave it to me. It's a piece of cake.	"
say -v Kyoko "	ニック，私はあなたにこれに目を通してほしい	"; say -v Karen "	Nick, I want you to look this over	"
say -v Kyoko "	私がそれを提出する前に．	"; say -v Karen "	before I turn it in. 	"
say -v Kyoko "	ごめん，しかし私は手が離せないんだ．今現在	"; say -v Karen "	Sorry, but I have my hands full right now.	"
say -v Kyoko "	私が間に合わなかったらどうなりますか、締切に．	"; say -v Karen "	What if I don't meet the deadline? 	"
say -v Kyoko "	きっと彼は腹をたてるだろう、あなたに	"; say -v Karen "	I bet he'll get mad at you.	"
say -v Kyoko "	君の要約は申し分ない	"; say -v Karen "	Your summary leaves nothing to be desired	"
say -v Kyoko "	ひどい字以外は	"; say -v Karen "	apart from the terrible handwriting.	"
say -v Kyoko "	君はよく考えるべきだ	"; say -v Karen "	You ought to think over	"
say -v Kyoko "	その前提が妥当かどうか	"; say -v Karen "	whether the premise is valid or not.	"
say -v Kyoko "	とりわけ，科学用語は必要とする	"; say -v Karen "	Above all, scientific terms call for	"
say -v Kyoko "	厳密な定義を	"; say -v Karen "	precise definitions.	"