#!/bin/bash

say -v Kyoko "	私たちは尊重しなければならない	"; say -v Karen "	We must respect	"
say -v Kyoko "	個人の意志を	"; say -v Karen "	the will of the individual	"
say -v Kyoko "	気楽にやれ．	"; say -v Karen "	Take it easy. 	"
say -v Kyoko "	私は保証します	"; say -v Karen "	I can assure you	"
say -v Kyoko "	すべてがうまくいくことを	"; say -v Karen "	that everything will turn out fine.	"
say -v Kyoko "	捨てよう	"; say -v Karen "	Let go of 	"
say -v Kyoko "	あなたの悲観的な人生観を	"; say -v Karen "	negative outlook on your life	"
say -v Kyoko "	常に維持しなさい	"; say -v Karen "	Always maintain	"
say -v Kyoko "	前向きな態度を	"; say -v Karen "	a positive attitude.	"
say -v Kyoko "	あなたは誰に対しても公平でなければならない	"; say -v Karen "	You should be fair to everyone	"
say -v Kyoko "	関係なく、生まれた国，性別，信条に	"; say -v Karen "	regardless of national origin, gender, or creed.	"
say -v Kyoko "	平等は保証されている	"; say -v Karen "	Equality is guaranteed	"
say -v Kyoko "	憲法で	"; say -v Karen "	by the Constitution.	"
say -v Kyoko "	彼は柱に寄りかかって見つめた	"; say -v Karen "	He leaned against the pillar and gaized	"
say -v Kyoko "	自由の女神像を	"; say -v Karen "	at the statue of Liberty.	"
say -v Kyoko "	一人の女性が僕の前を通り過ぎた	"; say -v Karen "	A woman passed by me 	"
say -v Kyoko "	ほのかな香りを発しながら．	"; say -v Karen "	giving off a subtle scent of perfume.	"
say -v Kyoko "	それは私に思い出させた、前の彼女を．	"; say -v Karen "	It reminded me of my ex-girlfriend.	"
say -v Kyoko "	納豆はひどい臭いがする	"; say -v Karen "	Natto smells awful	"
say -v Kyoko "	けど，素晴らしい味がする	"; say -v Karen "	but tastes terrific.	"
say -v Kyoko "	私はびしょ濡れだ、汗で．	"; say -v Karen "	I'm soaked with sweat. 	"
say -v Kyoko "	来ないで．あなたはくさい．シャワーを浴びて	"; say -v Karen "	Stand back. You stink. Take a shower.	"
