#!/bin/bash

say -v Kyoko "	何よりもまず，公式を暗記しなさい	"; say -v Karen "	First of all, learn the formula by heart.	"
say -v Kyoko "	体積を計算するためには，	"; say -v Karen "	To calculate the volume, 	"
say -v Kyoko "	縦と横と高さを掛けます	"; say -v Karen "	multiply the length by the width by the depth.	"
say -v Kyoko "	小さなひびが見つかった	"; say -v Karen "	Tiny cracks were found	"
say -v Kyoko "	樽の底に	"; say -v Karen "	in the bottom of the barrel.	"
say -v Kyoko "	この章では焦点をあてます	"; say -v Karen "	This chapter will focus on	"
say -v Kyoko "	幾何学の概念に	"; say -v Karen "	the concepts of geometry.	"
say -v Kyoko "	フィルは学問的なテーマに興味がある	"; say -v Karen "	Phil is much more interested in academic subjects	"
say -v Kyoko "	実用的な技術よりも	"; say -v Karen "	than in practical skills.	"
say -v Kyoko "	何かの調子が悪くなった、顕微鏡の．	"; say -v Karen "	Something's gone wrong with this microscope. 	"
say -v Kyoko "	私はそれを修理してもらう必要がある．	"; say -v Karen "	I need to have it repaired. 	"
say -v Kyoko "	ちょっと見せて．たぶん僕が直せます．	"; say -v Karen "	Let me see it. Maybe I can fix it.	"
say -v Kyoko "	インストゥルメントってなんですか．	"; say -v Karen "	What is 'an instrument? 	"
say -v Kyoko "	例えば，計器，温度計や気圧計のような	"; say -v Karen "	For instance, a gauge, such as a thermometer or a barometer.	"
say -v Kyoko "	その微粒子はかろうじて見える、肉眼で	"; say -v Karen "	The minute particles are barely visible to the naked eye.	"
say -v Kyoko "	筋肉組織は構成されている	"; say -v Karen "	Muscle tissue consists of	"
say -v Kyoko "	膨大な数の細胞から	"; say -v Karen "	a vast number of cells.	"
say -v Kyoko "	この物質は主に構成されている	"; say -v Karen "	This substance is mostly composed of 	"
say -v Kyoko "	水素と酸素で	"; say -v Karen "	hydrogen and oxygen.	"
say -v Kyoko "	正確な気温は22.68度です、セ氏	"; say -v Karen "	The exact temperature is 22.68 degrees Celsius.	"