#!/bin/bash

say -v Kyoko "	その講堂は空だった	"; say -v Karen "	The auditorium was empty 	"
say -v Kyoko "	たったひとつの家具を除いては	"; say -v Karen "	except for a single piece of furniture.	"
say -v Kyoko "	どんなマンションでも良いです	"; say -v Karen "	Any apartment will do 	"
say -v Kyoko "	家賃が安い限りは．	"; say -v Karen "	as long as the rent is low. 	"
say -v Kyoko "	私はこだわりがないですから、それについては	"; say -v Karen "	I'm not particular about it.	"
say -v Kyoko "	彼の６０歳のいとこは相続した	"; say -v Karen "	His sixty-year-old cousin inherited	"
say -v Kyoko "	一つの不動産を、湖畔の	"; say -v Karen "	a piece of real estate by a lake.	"
say -v Kyoko "	ここまでにしましょう、雑談は．	"; say -v Karen "	So much for small talk. 	"
say -v Kyoko "	取り掛かりましょう、仕事に	"; say -v Karen "	Let's get down to business.	"
say -v Kyoko "	ルーシーは腹を立てた、強引な販売員に	"; say -v Karen "	Lucy resented the aggressive salesman	"
say -v Kyoko "	契約書にサインさせようとする	"; say -v Karen "	trying to make her sign the contract.	"
say -v Kyoko "	たくさんの要因がある	"; say -v Karen "	There are a number of factors	"
say -v Kyoko "	私たちのやる気を失わせる、株式投資への	"; say -v Karen "	discouraging us from investing in stocks.	"
say -v Kyoko "	日本は様々な原料を輸入する	"; say -v Karen "	Japan imports various raw materials 	"
say -v Kyoko "	そして輸出する、工業製品を	"; say -v Karen "	and exports manufactured goods.	"
say -v Kyoko "	過程において、その経済発展の	"; say -v Karen "	In the course of its economic development,	"
say -v Kyoko "	日本は捨てた、伝統的価値観を	"; say -v Karen "	Japan has abandoned its traditional values.	"
say -v Kyoko "	世界は直面している、かつてない危機に	"; say -v Karen "	The world is faced with an unprecedented crisis.	"
say -v Kyoko "	要するに	"; say -v Karen "	In short,	"
say -v Kyoko "	目的は、その規制の	"; say -v Karen "	the purpose of the regulations	"
say -v Kyoko "	国内産業を保護することだ	"; say -v Karen "	is to protect domestic industries.	"
say -v Kyoko "	維持するために、世界での競争力を	"; say -v Karen "	In order to keep up its competitiveness in the world,	"
say -v Kyoko "	日本は着手しなければならない	"; say -v Karen "	Japan must undertake	"
say -v Kyoko "	大幅な規制緩和に、真剣に	"; say -v Karen "	sweeping deregulation in earnest.	"