#!/bin/bash

say -v Kyoko "	ボブが割り込んできた、私たちの会話に、言いながら	"; say -v Karen "	Bob cut in on our conversation, saying,	"
say -v Kyoko "	私は反対だ，それには．	"; say -v Karen "	I'm against it. 	"
say -v Kyoko "	しかし，全員が無視した，彼を，	"; say -v Karen "	But everybody ignored him.	"
say -v Kyoko "	私たちは飛ばした，彼の順番を	"; say -v Karen "	We skipped his turn	"
say -v Kyoko "	わざと．	"; say -v Karen "	on purpose.	"
say -v Kyoko "	彼は見た、誰かがいじめられているのを，	"; say -v Karen "	He saw someone being bullied,/	"
say -v Kyoko "	しかし，彼は見て見ぬふりをした	"; say -v Karen "	but he turned a blind eye.	"
say -v Kyoko "	ニックと僕がカンニングした時、試験で，	"; say -v Karen "	When Nick and I cheated on the exam,/	"
say -v Kyoko "	僕は停学になった．	"; say -v Karen "	I was suspended from school. 	"
say -v Kyoko "	ニックはと言うと，	"; say -v Karen "	As for Nick,/	"
say -v Kyoko "	彼はそれをまんまと逃れた．	"; say -v Karen "	he got away with it.	"
say -v Kyoko "	彼らは敵意を抱いてる、リチャードに	"; say -v Karen "	They are hostile/to Richard/	"
say -v Kyoko "	なぜなら彼らは嫉妬している、彼の富と地位に	"; say -v Karen "	because they are jealous of/his wealth and status.	"
say -v Kyoko "	私は彼が大嫌い．	"; say -v Karen "	I hate him. 	"
say -v Kyoko "	彼は振る舞う	"; say -v Karen "	He behaves	"
say -v Kyoko "	まるで彼が大物であるかのように	"; say -v Karen "	as if he were somebody.	"
say -v Kyoko "	私たちの褒め言葉にもかかわらず，	"; say -v Karen "	In spite of our compliments,/ 	"
say -v Kyoko "	彼は顔をしかめて顔を背けた．	"; say -v Karen "	he frowned and turned away. 	"
say -v Kyoko "	彼はとても失礼だ．	"; say -v Karen "	He was so rude.	"
say -v Kyoko "	彼は主張した	"; say -v Karen "	He claimed/	"
say -v Kyoko "	膨大な財産は彼の自由にできると	"; say -v Karen "	that the enourmous property was at his disposal.	"
say -v Kyoko "	頑固になればなるほど	"; say -v Karen "	The more stubborn you are/	"
say -v Kyoko "	あなたは孤立します	"; say -v Karen "	 the more isolated you become.	"
say -v Kyoko "	話を焦らすのはやめてくれ．私にどうしろというのか．	"; say -v Karen "	Don't beat around the bush! What am I supposed to do? 	"
say -v Kyoko "	慌てずに待つしかない．時が経てばわかる	"; say -v Karen "	Just wait and see. Time will tell.	"