#!/bin/bash

say -v Kyoko "	時が熟したら，	"; say -v Karen "	When the time is ripe,	"
say -v Kyoko "	大胆にそれを手に入れろ．	"; say -v Karen "	be bold and go for it. 	"
say -v Kyoko "	僕が見捨てない，君を	"; say -v Karen "	I'll stand by you.	"
say -v Kyoko "	私は立ち上がる，私が信じるもののために	"; say -v Karen "	I'll stand up for what I believe in	"
say -v Kyoko "	そして屈しない，いかなる脅威にも	"; say -v Karen "	and won't yield to any threats.	"
say -v Kyoko "	私が弱点を克服できさえすればいいのになあ．	"; say -v Karen "	If only I could conquer my weaknesses. 	"
say -v Kyoko "	それはアナタ次第だ	"; say -v Karen "	It's up to you.	"
say -v Kyoko "	あなたは最大限利用するべきだ，この滅多にない機会を	"; say -v Karen "	You should make the most of this rare opportunity	"
say -v Kyoko "	実証するために，あなたの才能を	"; say -v Karen "	to demonstrate your talent.	"
say -v Kyoko "	あなたは僕をがっかりさせない．	"; say -v Karen "	You won't let me down. 	"
say -v Kyoko "	私は信頼してる，あなたを．君は成功するよ	"; say -v Karen "	I have great faith in you. You can make it.	"
say -v Kyoko "	観客たちは感動した	"; say -v Karen "	The spectators were moved	"
say -v Kyoko "	彼女の優雅な演技に	"; say -v Karen "	by her graceful performance.	"
say -v Kyoko "	1995年，安藤氏は受け取った，建築学の最も権威のある賞を	"; say -v Karen "	In 1995, Anso received architecture's most prestigious award.	"
say -v Kyoko "	逆境をものともせず，	"; say -v Karen "	In the face of adversity,	"
say -v Kyoko "	マイクは成し遂げた，並外れた偉業を．	"; say -v Karen "	Mike accomplished an extraordinary feat. 	"
say -v Kyoko "	彼は受けるに値する，賞賛を	"; say -v Karen "	He deserves praise.	"
say -v Kyoko "	聴衆は感銘を受けた，彼の説得力ある講演に	"; say -v Karen "	The audience was impressed by his eloquent lecture.	"
say -v Kyoko "	庶民の身から，	"; say -v Karen "	From a humble background,	"
say -v Kyoko "	ジョンは成し遂げた，世界的な名声を	"; say -v Karen "	John achieved worldwide fame.	"
say -v Kyoko "	彼は蓄積した，莫大な財産を	"; say -v Karen "	He accumulated a tremendous fortune	"
say -v Kyoko "	戦後の時代の間に	"; say -v Karen "	during the postwar era.	"
say -v Kyoko "	彼は以前は裕福で気前が良かった	"; say -v Karen "	He used to be well off and generous,	"
say -v Kyoko "	しかし今彼はその日暮らしをする	"; say -v Karen "	but now he lives from hand to mouth.	"