#!/bin/bash

say -v Kyoko "	明らかに，	"; say -v Karen "	Obviously,	"
say -v Kyoko "	広告は狙いとしている，10代の若者を	"; say -v Karen "	the advertisement is aimed at teenagers.	"
say -v Kyoko "	その工場，現在建設中のは	"; say -v Karen "	The factory now under construction	"
say -v Kyoko "	1000台のビデオデッキを組み立てるだろう、一日あたり	"; say -v Karen "	will assemble 1,000 VCR units per day.	"
say -v Kyoko "	効率的な機械が取って代わった、肉体労働に	"; say -v Karen "	Efficient machinery replaced manual labor.	"
say -v Kyoko "	当時	"; say -v Karen "	In those days,	"
say -v Kyoko "	その巨大な企業は事実上の独占を持っていた、国内の商業を	"; say -v Karen "	the gigantic corporation had a virtual monopoly over internal commerce.	"
say -v Kyoko "	制限が取り除かれたので	"; say -v Karen "	With restrictions removed,	"
say -v Kyoko "	数千の新しい企業が誕生した	"; say -v Karen "	thousands of new enterprises have come into being.	"
say -v Kyoko "	彼の馬鹿げた新規事業の結果，	"; say -v Karen "	As a result of his ridiculous veture,	"
say -v Kyoko "	彼は危険な状態にある、倒産の	"; say -v Karen "	he is in danger of going bankrupt.	"
say -v Kyoko "	昨年と比較して，	"; say -v Karen "	Compared to the previous year,	"
say -v Kyoko "	事業は上向いている、売上の点で．	"; say -v Karen "	business is looking up in terms of sales. 	"
say -v Kyoko "	しかしながら，私達はまだ儲けていない	"; say -v Karen "	However, we haven't made any profit yet	"
say -v Kyoko "	私は転任させられるだろう、海外の支店に．	"; say -v Karen "	I'm going to be transferred to  an overseas branch. 	"
say -v Kyoko "	えっ，私はあなたがいなくて寂しい．手紙を書いてください	"; say -v Karen "	Oh, I'll miss you. Please drop me a line.	"
say -v Kyoko "	彼がいない間, 仕事で	"; say -v Karen "	While he was away on business,	"
say -v Kyoko "	彼の妻は出産した, 男の赤ちゃんを	"; say -v Karen "	his wife gave birth to a baby boy.	"