#!/bin/bash

say -v Kyoko "	すいません．どのくらいの頻度ですか，シャトルバスがニューヨーク市街に行くのは	"; say -v Karen "	Excuse me. How often do the shuttle buses run to downtown New York?	"
say -v Kyoko "	そのモーテルは収容できる，400人もの客を	"; say -v Karen "	The motel can accommodate as many as 400 guests.	"
say -v Kyoko "	このスイートルームは3倍大きい，私のマンションより	"; say -v Karen "	This suite is three times larger than my condominium.	"
say -v Kyoko "	ゴミの投げ捨て，この施設内でのは、受ける場合がある	"; say -v Karen "	Littering in this facility is subjected to	"
say -v Kyoko "	最大で500ドルの罰金を	"; say -v Karen "	a maximum fine of $500.	"
say -v Kyoko "	そのレストランはいつも混んでいる．	"; say -v Karen "	That restaurant is always packed. 	"
say -v Kyoko "	私たちは予約した方がいい，事前に	"; say -v Karen "	We'd better make a reservation/beforehand.	"
say -v Kyoko "	中断してごめん，食事の	"; say -v Karen "	Sorry to interupt your meal	"
say -v Kyoko "	しかし私は相談したい，内密に．	"; say -v Karen "	but I'd like a work with you in private. 	"
say -v Kyoko "	私は連絡し直して良い，あとで	"; say -v Karen "	Can I get back to you later?	"
say -v Kyoko "	その料理人は驚いた、彼の信じられない食欲に	"; say -v Karen "	The cook was astonished at his incredible appetite.	"
say -v Kyoko "	何が起こっているんだ，下で．	"; say -v Karen "	What's going on down there? 	"
say -v Kyoko "	私は知りたがっている．よくわかりません	"; say -v Karen "	I'm curious. I have no idea.	"
say -v Kyoko "	興奮したファンが群がっていた，裏口に	"; say -v Karen "	Excited fans were hanging around the rear exit	"
say -v Kyoko "	一瞬目にすることを望んで，マイケルを	"; say -v Karen "	hoping to catch a glinpse of Michael.	"
say -v Kyoko "	有名人に出会うとすぐに，	"; say -v Karen "	On encoutering the celebrity,	"
say -v Kyoko "	彼らはサインを求めた	"; say -v Karen "	they asked for his autograph.	"