#!/bin/bash

say -v Kyoko "	私は海外に行くときはいつも	"; say -v Karen "	Wherever I go abroad,	"
say -v Kyoko "	私は苦しむ，時差ボケと下痢に	"; say -v Karen "	I suffer from jet lag and diarrhea.	"
say -v Kyoko "	私はちょっとめまいを感じる	"; say -v Karen "	I feel sort of dizzy	"
say -v Kyoko "	そして私は吐きたい気がする．	"; say -v Karen "	and I feel like throwing up. 	"
say -v Kyoko "	あなたは顔色が悪い	"; say -v Karen "	You look pale.	"
say -v Kyoko "	鎮痛剤を飲みなさい．	"; say -v Karen "	Take some aspirin. 	"
say -v Kyoko "	それはあなたの頭痛を治します，すぐに．	"; say -v Karen "	It will cure you of your headache in no time.	"
say -v Kyoko "	もしかしたら体調を崩したかなあ．	"; say -v Karen "	I'm afraid I'm coming down with something. 	"
say -v Kyoko "	あなたは休みを取った方がいい，一日	"; say -v Karen "	You should take a day off.	"
say -v Kyoko "	幾つかの成分，この飲料のは有害である，	"; say -v Karen "	Some of the ingredients in this beverage are harmful, 	"
say -v Kyoko "	特にあなたが妊娠してるなら	"; say -v Karen "	especially if you are pregnant.	"
say -v Kyoko "	十分な栄養摂取は極めて重要である、幼児の発育にとって	"; say -v Karen "	Good nutrition is vital for an infant's growth.	"
say -v Kyoko "	適度な運動は刺激する、血液の循環を	"; say -v Karen "	Moderate exercise stimulates the circulation of the blood.	"
say -v Kyoko "	医者は私に忠告した、控えるように，アルコールを	"; say -v Karen "	My physician advised me to refrain from alcohol	"
say -v Kyoko "	当分の間は	"; say -v Karen "	for the time being.	"
say -v Kyoko "	私は本当に体調を良くしたいし，減量したい，	"; say -v Karen "	I do want to get into shape and lose some weight,	"
say -v Kyoko "	なので私は泳ぎに行きます，毎朝	"; say -v Karen "	so I go swimming every morning.	"
say -v Kyoko "	彼はとても不快な風邪を引いた	"; say -v Karen "	He caught a nasty cold	"
say -v Kyoko "	なぜなら彼は夜更かしした，昨晩	"; say -v Karen "	because he stayed up late last night.	"
say -v Kyoko "	外科医は彼を説得した	"; say -v Karen "	The surgeon persuaded him	"
say -v Kyoko "	臓器移植手術を受けることを	"; say -v Karen "	to undergo an organ transplant.	"
say -v Kyoko "	私の父は寝たきりなので	"; say -v Karen "	Since our father is bedridden, 	"
say -v Kyoko "	私たちは交代で面倒を見ています，彼の	"; say -v Karen "	we take turns looking after him.	"
say -v Kyoko "	私たちの仮説は	"; say -v Karen "	Our hypothesis is that	"
say -v Kyoko "	過度の量のジャンクフードを食べることは	"; say -v Karen "	eating excessive amounts of junk food	"
say -v Kyoko "	早死の一因になるということだ	"; say -v Karen "	contributes to early mortality.	"
say -v Kyoko "	政府は適切な手段を取らなかった	"; say -v Karen "	The government did not take appropriate measures	"
say -v Kyoko "	感染が拡大することを防ぐための	"; say -v Karen "	to prevent the infection from spreading.	"
say -v Kyoko "	大臣は余儀なくされた，辞職することを、内閣から	"; say -v Karen "	The minister was obliged to resign from the Cabinet.	"