#!/bin/bash

say -v Kyoko "	生態学者は私たちに警告している、何度も何度も	"; say -v Karen "	The ecologist has warned us time and again	"
say -v Kyoko "	石油は天の恵みだけでなく災のもとでもあると	"; say -v Karen "	that petroleum is not only a blessing but also a curse.	"
say -v Kyoko "	その大陸は豊富だ、化石燃料が	"; say -v Karen "	The continent is abundant in fossil fuels.	"
say -v Kyoko "	その地域は比較的豊かだ、鉱物資源が	"; say -v Karen "	The region is relatively rich in mineral resources.	"
say -v Kyoko "	小麦は占める、およそ3分の2の農業生産高の、この地域の	"; say -v Karen "	Wheat accounts for approximately two-thirds agricultural production in the area.	"
say -v Kyoko "	肥沃な土壌は不可欠だ、良い収穫のために	"; say -v Karen "	Fertile soul is indispensable for a good harvest.	"
say -v Kyoko "	湿気の多い気候は特色だ、その半島の	"; say -v Karen "	A humid climate is characteristic of the peninsula.	"
say -v Kyoko "	その活火山は噴火する、定期的な感覚で	"; say -v Karen "	The active volcano erupts at regular intervals.	"
say -v Kyoko "	パナマ運河はつなぐ、大西洋と太平洋を	"; say -v Karen "	The Panama Canal connects the Atlantic with the Pacific.	"
say -v Kyoko "	その地理的特徴、ここの、は似ている	"; say -v Karen "	The geographical features here are similar to 	"
say -v Kyoko "	私たちの県のそれと	"; say -v Karen "	those of our prefecture.	"
say -v Kyoko "	たいてい、飢饉は伴う、疫病を	"; say -v Karen "	More often than not, famine is accompanied by plague.	"
say -v Kyoko "	壊滅的な地震が州都を襲い，	"; say -v Karen "	A devastating earthquake hit the state capital,	"
say -v Kyoko "	数万人の住民を家のない状態にした	"; say -v Karen "	leaving tens of thousands of residents homeless.	"
say -v Kyoko "	気をつけろ！天井が崩れかけている	"; say -v Karen "	Watch out. The ceiling is giving way.	"
say -v Kyoko "	天気予報は言っている	"; say -v Karen "	The weather forecast says	"
say -v Kyoko "	台風は加速して沿岸に近づきそうだと	"; say -v Karen "	the typhoon is likely to accelerate and approach the coast.	"
say -v Kyoko "	それはまだ決まっていない	"; say -v Karen "	It's still up in the air	"
say -v Kyoko "	試合が中止になるかどうか．	"; say -v Karen "	whether the game will be called off or not. 	"
say -v Kyoko "	それがどうした．私にとってはどちらでも同じだ	"; say -v Karen "	So what? It makes no difference to me.	"
say -v Kyoko "	霧が濃いね．	"; say -v Karen "	It's foggy, isn't it? 	"
say -v Kyoko "	全く本当だ．	"; say -v Karen "	It sure is. 	"
say -v Kyoko "	しかし，たぶん晴れるだろう、この後に	"; say -v Karen "	But chances are it'll clear up later on.	"