#!/bin/bash

say -v Kyoko "	多くの人は考えている	"; say -v Karen "	Many people regard	"
say -v Kyoko "	現在の義務教育制度が時代遅れであると	"; say -v Karen "	the current compulsory education system as being obsolete.	"
say -v Kyoko "	多くの人が私を励ました	"; say -v Karen "	Many people encouraged me	"
say -v Kyoko "	大きな目標を実現するように	"; say -v Karen "	to fulfill my ambitions.	"
say -v Kyoko "	彼の夢を実現するために，	"; say -v Karen "	To make his dreams come true,	"
say -v Kyoko "	彼は学校を中退して東京を目指した．	"; say -v Karen "	he dropped out of school and made his way to Tokyo.	"
say -v Kyoko "	普段は何をなさっているのですか？	"; say -v Karen "	What do you do? 	"
say -v Kyoko "	私は大学生です，一年ですハーバードの．	"; say -v Karen "	I'm college student, a fresh man at Harvard. 	"
say -v Kyoko "	専攻は？哲学です	"; say -v Karen "	What's your major? Philosophy.	"
say -v Kyoko "	授業料は値上げされる，ほぼ10％，4月1日，2001年の	"; say -v Karen "	Tuition will be raised by nearly ten percent as of April, 2001.	"
say -v Kyoko "	私はどちらにしようか悩んでいる，申し込もうかどうか，奨学金を．	"; say -v Karen "	I'm of two minds whether to apply for the scholarship or not. 	"
say -v Kyoko "	やってみなよ	"; say -v Karen "	Give it a try.	"
say -v Kyoko "	彼は慶應大学を卒業するとすぐに，	"; say -v Karen "	As soon as he graduated from Keio University,	"
say -v Kyoko "	彼は家族の仕事を引き継いだ	"; say -v Karen "	he took over his family's business.	"
say -v Kyoko "	あなたは向いていない，軍隊には	"; say -v Karen "	You aren't cut out for the military	"
say -v Kyoko "	厳格な規律が理由で．	"; say -v Karen "	because of its rigid discipline.	"
say -v Kyoko "	私は決心する，生計を立てると	"; say -v Karen "	I am determined to make a living 	"
say -v Kyoko "	脚本家として、どんな犠牲を払っても	"; say -v Karen "	as a playwright at all costs.	"
say -v Kyoko "	彼が大人になって，	"; say -v Karen "	As he grew up,	"
say -v Kyoko "	彼はできるようになった，総合的な視野で捉えることが	"; say -v Karen "	he learned to put thing in perspective.	"
say -v Kyoko "	体制に従うことは不可欠な要素だ	"; say -v Karen "	Comformity is an essential element	"
say -v Kyoko "	私たちの均質な地域社会では	"; say -v Karen "	of our homogeneous community.	"
say -v Kyoko "	私は我が道を行きたい	"; say -v Karen "	I'd rather go my own way	"
say -v Kyoko "	あくせく働くよりは，会社で．	"; say -v Karen "	than toil away from company. 	"
say -v Kyoko "	型にはまろうとすることはなんの成果ももたらさない	"; say -v Karen "	Trying to fit into a mold gets me nowhere.	"
say -v Kyoko "	トムは似ている，おじに，性格が．	"; say -v Karen "	Tom takes after his uncle in personality. 	"
say -v Kyoko "	つまり，彼は頑固だ，生まれつき．	"; say -v Karen "	I mean, he is obstinate by nature. 	"
say -v Kyoko "	彼は決して屈服しない	"; say -v Karen "	He never gives in.	"