#!/bin/bash

say -v Kyoko "	どうやら,ニックは引き受けたがらなかった, その仕事を	"; say -v Karen "	Apparently, Nick wasn't willing to take on the task	"
say -v Kyoko "	なぜならそれは彼の負担を増やすから	"; say -v Karen "	because it would just add to his burdens	"
say -v Kyoko "	ボブはデートするつもりだった、彼女と今夜，	"; say -v Karen "	Bob had intended to take her out tonight,	"
say -v Kyoko "	しかし彼は残業しなければならなかった	"; say -v Karen "	but he had to work overtime.	"
say -v Kyoko "	損失を見積もってください、金曜までに、遅くとも．	"; say -v Karen "	Please estimate the losses by Friday at the latest. 	"
say -v Kyoko "	私はなんとかするでしょう	"; say -v Karen "	I'll manage it somehow.	"
say -v Kyoko "	ニック，私はあなたを頼りにしてる．	"; say -v Karen "	Nick, I'm counting on you. 	"
say -v Kyoko "	大丈夫，私はきちんとそれをやります．	"; say -v Karen "	OK, I'll see to it. 	"
say -v Kyoko "	ありがとう，感謝します．どういたしまして．	"; say -v Karen "	Thanks, I appreciate it. Don't mention it.	"
say -v Kyoko "	彼は熱心な振りをする	"; say -v Karen "	He pretends to be enthusiastic	"
say -v Kyoko "	彼の上司がそばにいる時	"; say -v Karen "	when his boss is arouond.	"
say -v Kyoko "	彼は昇進した、彼の同僚を犠牲にして．	"; say -v Karen "	He got promoted at the expense of his colleagues. 	"
say -v Kyoko "	彼は恥ずかしく思うべきだ，自分自身を	"; say -v Karen "	He should be ashamed of himself.	"
say -v Kyoko "	景気後退が始まると，	"; say -v Karen "	As the recession set in,	"
say -v Kyoko "	短期契約社員は解雇された、次々と	"; say -v Karen "	temporary employees were laid off one after another.	"
say -v Kyoko "	今日では，	"; say -v Karen "	Nowadays,	"
say -v Kyoko "	多くの人々が失業中である、彼らの意志に反して．	"; say -v Karen "	many people are out of work against their will. 	"
say -v Kyoko "	誰がその責任を負うべきか	"; say -v Karen "	Who is responsible for that?	"
say -v Kyoko "	私は悲観的になっていて，	"; say -v Karen "	I've gotten pessimistic,	"
say -v Kyoko "	そして私は何かを心配している	"; say -v Karen "	and I'm worried about something	"
say -v Kyoko "	私が決して心配しなかったことを，以前は	"; say -v Karen "	I would never have been concerned about before.	"
say -v Kyoko "	今日では，オフィス労働者でさえ直面している、大変な困難に	"; say -v Karen "	Today, even white-collar workers are confronted with great hardships.	"
say -v Kyoko "	当局は懸命に努力している、無駄に	"; say -v Karen "	The authorities are striving in vain	"
say -v Kyoko "	通貨を安定させるために	"; say -v Karen "	to stabilize the currency.	"
say -v Kyoko "	我々は結論に至った	"; say -v Karen "	We've come to the conclusion	"
say -v Kyoko "	緊急を要することは何もない	"; say -v Karen "	that nothing is more urgent	"
say -v Kyoko "	日本の膨大な赤字を削減すること以外に	"; say -v Karen "	than reducing Japan's huge deficit.	"