#!/bin/bash

say -v Kyoko "	彼は力説する	"; say -v Karen "	He contends	"
say -v Kyoko "	原始的な生物がかつて存在したと、火星に	"; say -v Karen "	that primitive life once existed on Mars.	"
say -v Kyoko "	乗組員たちは忙しく準備している	"; say -v Karen "	The crew is busy preparing	"
say -v Kyoko "	宇宙への航海の	"; say -v Karen "	for the voyage into outer space.	"
say -v Kyoko "	彼らは実施した、一連の実験を	"; say -v Karen "	They conducted a series of experiments	"
say -v Kyoko "	無重力状態で	"; say -v Karen "	under zero gravity.	"
say -v Kyoko "	多くの天文学者が考えている	"; say -v Karen "	Many astronomers assume	"
say -v Kyoko "	宇宙は無限に膨張していると	"; say -v Karen "	that the universe will expand infinitely.	"
say -v Kyoko "	宇宙飛行士たちは迎えられた	"; say -v Karen "	The astronauts were greeted	"
say -v Kyoko "	自然と生じた拍手で	"; say -v Karen "	 with spontaneous applause.	"
say -v Kyoko "	ある基金が設立された	"; say -v Karen "	A fund was set up	"
say -v Kyoko "	保存するつもりで	"; say -v Karen "	with a view to preserving	"
say -v Kyoko "	私たちの絶滅の危機にひんした地球を	"; say -v Karen "	our endangered planet.	"
say -v Kyoko "	大洪水が麻痺させた	"; say -v Karen "	The massive flood paralyzed	"
say -v Kyoko "	現地の交通網を	"; say -v Karen "	the local transportation network.	"
say -v Kyoko "	赤道は地球を分ける	"; say -v Karen "	The equator divides the globe	"
say -v Kyoko "	2つの半球に	"; say -v Karen "	into two hemispheres.	"
say -v Kyoko "	私は思う、それは残酷であると	"; say -v Karen "	I think it's cruel	"
say -v Kyoko "	動物を罠で捕らえるのは、毛皮のコートのために	"; say -v Karen "	to trap animals for fur coats.	"
say -v Kyoko "	その団体はもっとも重要な役割を果たしている	"; say -v Karen "	The organization plays a principal role	"
say -v Kyoko "	野生動物の保護において	"; say -v Karen "	in wildlife conservation.	"
say -v Kyoko "	多くの弱い生物種が寸前である、絶滅の	"; say -v Karen "	Many fragile species are on the verge of extinction.	"
say -v Kyoko "	長引く干ばつが深刻な被害をもたらした/収穫に	"; say -v Karen "	The prolonged drought did severe damage to the crops.	"
say -v Kyoko "	熱帯雨林が急速に消失している、地球規模で．	"; say -v Karen "	Tropical rain forests are quickly disappearing on a global scale. 	"
say -v Kyoko "	一部は、酸性雨が原因で	"; say -v Karen "	In part, it's due to acid rain.	"
say -v Kyoko "	言われている、地球温暖化は直接に関連付けられると	"; say -v Karen "	It is said that global warming is directly related	"
say -v Kyoko "	二酸化炭素の排出と	"; say -v Karen "	to carbon dioxide emissions.	"
say -v Kyoko "	オゾン層の破壊は影響を及ぼす、環境に	"; say -v Karen "	The destruction of the ozone layer affects the environment.	"
say -v Kyoko "	委員会は各国に要求した	"; say -v Karen "	The committee called on all nations	"
say -v Kyoko "	協力しあって仕事することを	"; say -v Karen "	to work side by side	"
say -v Kyoko "	大気汚染を抑制するために	"; say -v Karen "	to curb air pollution.	"
say -v Kyoko "	人工衛星が打ち上げられた、軌道に	"; say -v Karen "	A satellite was launched into orbit	"
say -v Kyoko "	溶け続ける氷河を監視するために	"; say -v Karen "	to monitor melting glaciers.	"