#!/bin/bash

say -v Kyoko "	ボブはひどく取り乱していた	"; say -v Karen "	Bob was so beside himself	"
say -v Kyoko "	ので，彼はほとんど区別ができなかった	"; say -v Karen "	that he could scarcely tell	"
say -v Kyoko "	現実と虚構の	"; say -v Karen "	fact from fiction.	"
say -v Kyoko "	彼の新しい小説は	"; say -v Karen "	His new novel, 	"
say -v Kyoko "	散文と彼の詩の才能を組み合わせた	"; say -v Karen "	which conbines prose with his gift for poetry	"
say -v Kyoko "	出版される予定だ．	"; say -v Karen "	is going to be published.	"
say -v Kyoko "	最新版の百科事典は	"; say -v Karen "	An up-to-date edition of encyclopedia 	"
say -v Kyoko "	出版される、来月	"; say -v Karen "	will come out next month.	"
say -v Kyoko "	山田さんは翻訳した	"; say -v Karen "	Ms. Yamada translated 	"
say -v Kyoko "	魅力的なおとぎ話を平易な日本語に	"; say -v Karen "	the fascinating fairy tale into plain Japanese.	"
say -v Kyoko "	以下の一節は引用された	"; say -v Karen "	The following passage is quoted	"
say -v Kyoko "	有名な寓話から	"; say -v Karen "	from a well-known fable.	"
say -v Kyoko "	あなたはよく知っていますか、現代文学を．	"; say -v Karen "	Are you familiar with contemporary literature? 	"
say -v Kyoko "	私はほとんど知りません、それについては	"; say -v Karen "	I know next to nothing about it.	"
say -v Kyoko "	時々	"; say -v Karen "	At times	"
say -v Kyoko "	私は混同する、curveとcarveを	"; say -v Karen "	I confuse curve with carve.	"
say -v Kyoko "	恥ずかしがらないで．	"; say -v Karen "	Don't be shy. 	"
say -v Kyoko "	あなたの発音は大体合っています	"; say -v Karen "	Your pronunciation is more or less correct.	"
say -v Kyoko "	この記事は役立つ情報を含んでいます	"; say -v Karen "	This article contains tips	"
say -v Kyoko "	熱心な人達に、語彙を増やすことに	"; say -v Karen "	for those who are eager to increase their vocablary.	"
say -v Kyoko "	彼の最新の作品は展示されている、市庁舎で．	"; say -v Karen "	His latest works are on display at the city hall. 	"
say -v Kyoko "	それらは素敵です、言葉で表せないほど	"; say -v Karen "	They are fabulous beyond description.	"
say -v Kyoko "	席を詰めてもらえませんか、少し．	"; say -v Karen "	Could you move over a little? 	"
say -v Kyoko "	ごめんなさい．私は気づきませんでした	"; say -v Karen "	Oh, sorry. I didn't realize	"
say -v Kyoko "	私がそんなにたくさんの場所を取っていたことに	"; say -v Karen "	I was taking up so much space.	"
say -v Kyoko "	何この不格好な物体は．	"; say -v Karen "	What's this ugly object? 	"
say -v Kyoko "	これは一つの抽象芸術だよ	"; say -v Karen "	This is a piece of abstract art!	"
say -v Kyoko "	私はリッチーに頼んだ	"; say -v Karen "	I begged Richie	"
say -v Kyoko "	１００ドル貸してくれるように	"; say -v Karen "	to lend me a hundred bucks,	"
say -v Kyoko "	しかし，彼は首を横に振った、言いながら	"; say -v Karen "	but he shook his head, saying	"
say -v Kyoko "	オレもお金がないと	"; say -v Karen "	I'm broke, too.	"