#!/bin/bash

say -v Kyoko "	ほとんどの場合	"; say -v Karen "	For the omst part,	"
say -v Kyoko "	近代化は同じものだと考えられる、西欧化と	"; say -v Karen "	modernization is identified with westernization.	"
say -v Kyoko "	都会の文化は魅力的に見える、多くの人に，	"; say -v Karen "	Urban culture appears to be attractive to many people,	"
say -v Kyoko "	とりわけ若者にとっては	"; say -v Karen "	in particular, to younger people.	"
say -v Kyoko "	AIは略です、人工知能の	"; say -v Karen "	AI stands for artificial intelligence.	"
say -v Kyoko "	家庭用電化製品は便利になっている、日に日に	"; say -v Karen "	Household appliances are becoming more convenient day by day.	"
say -v Kyoko "	私の収入は十分ではない、4人家族を養うのに	"; say -v Karen "	My income is not adequate to provide for my family of four,	"
say -v Kyoko "	しかし私たちはそれでなんとかやっていかなければならない	"; say -v Karen "	but we have to make the best of it.	"
say -v Kyoko "	ホームページの人気は内容によって決まる	"; say -v Karen "	The popularity of a website depends on its contents.	"
say -v Kyoko "	あなたはそれに遅れずについていかなきゃ．	"; say -v Karen "	You've got to keep up with it. 	"
say -v Kyoko "	いったんあなたが遅れをとってしまうと，追いつくのは難しい	"; say -v Karen "	Once you fall behind, it's hard to catch up.	"
say -v Kyoko "	技術は急速に進歩するので	"; say -v Karen "	As technology rapidly advances,	"
say -v Kyoko "	それは難しい、遅れずについていくのは	"; say -v Karen "	it's tough to keep pace with it.	"
say -v Kyoko "	ますます多くの人々が焦っている	"; say -v Karen "	More and more people are rushing	"
say -v Kyoko "	双方向性の性質を利用することに、その媒体の	"; say -v Karen "	to make use of the interactive nature of the medium.	"
say -v Kyoko "	革新は能力と関係がある	"; say -v Karen "	Innovation has something to do with the ability	"
say -v Kyoko "	普通でない現象に気づく	"; say -v Karen "	to notice unusual phenomena.	"
say -v Kyoko "	たくさんの他社が真似している、私たちの優れた方法を	"; say -v Karen "	A bunch of other companies are imitating our excellent methods.	"
say -v Kyoko "	かつての荒涼とした盆地が一変された	"; say -v Karen "	The once desolate valley was transformed	"
say -v Kyoko "	繁栄している中心地に、ハイテクビジネスの	"; say -v Karen "	into a thriving hub of hi-tech business.	"
say -v Kyoko "	まだたくさんの余地があるけれども、改善の，	"; say -v Karen "	Although there's still plenty of room for improvement,	"
say -v Kyoko "	彼の発明品は優れている、従来の機器よりも	"; say -v Karen "	his invention is superior to conventional equipment	"
say -v Kyoko "	あらゆる点で	"; say -v Karen "	in every respect.	"
say -v Kyoko "	その会社の強さは起因している	"; say -v Karen "	The strength of the firm is attributed	"
say -v Kyoko "	他にはない未来志向の戦略によって	"; say -v Karen "	to its unique and future-oriented strategies.	"
say -v Kyoko "	ソニーは統合した	"; say -v Karen "	SONY has integrated	"
say -v Kyoko "	広い範囲の機能をこのカッコイイ機器に．	"; say -v Karen "	a wide range of functions into this cool gadget. 	"
say -v Kyoko "	それは流行り始めている、全米で．	"; say -v Karen "	It's catchig on from coast to coast.	"
say -v Kyoko "	この道具は役に立つ	"; say -v Karen "	This tool comes in handy	"
say -v Kyoko "	なので私はいつもそれを近くにおいている	"; say -v Karen "	so I always keep it close at hand.	"
say -v Kyoko "	一般的に	"; say -v Karen "	In general,	"
say -v Kyoko "	消費者は量より質を好む．	"; say -v Karen "	consumers prefer quantity to quality. 	"
say -v Kyoko "	それは正反対です，今日では	"; say -v Karen "	It's the other way around today.	"