#!/bin/bash

say -v Kyoko "	ニックは決して満足しない，その報酬に．	"; say -v Karen "	Nick is by no means satisfied with the reward. 	"
say -v Kyoko "	彼は自己中心的で欲深い．	"; say -v Karen "	He is selfish and greedy.	"
say -v Kyoko "	あなたは借りがある私に全部で200ドル，ボブ．	"; say -v Karen "	You owe me $200 altogether, Bob. 	"
say -v Kyoko "	あなたはいつ返すつもり？	"; say -v Karen "	When are you going to pay me back? 	"
say -v Kyoko "	ごめん，私はお金に困ってるんだ．またそれだ．	"; say -v Karen "	I'm sorry. I'm hard up. There you go again.	"
say -v Kyoko "	ブライアンが驚いた事に，	"; say -v Karen "	To Brian's surprise,	"
say -v Kyoko "	これの借金が達していた，かなりの金額に	"; say -v Karen "	his debt amounted to a considerable sum.	"
say -v Kyoko "	やめろ，過去の栄光にしがみつくのは．	"; say -v Karen "	Stop clinging to your glory days,	"
say -v Kyoko "	さもないとあなたは取り残される	"; say -v Karen "	or you'll be left behind.	"
say -v Kyoko "	あなたは逃れられない，今日の厳しい現実から，	"; say -v Karen "	You cannot escape from today's harsh realities,	"
say -v Kyoko "	だからあなたは適応しなければならない，それに	"; say -v Karen "	so you must adapt to them.	"
say -v Kyoko "	繁栄は続かない，永遠には．	"; say -v Karen "	Prosperity does not last forever. 	"
say -v Kyoko "	つまり，	"; say -v Karen "	In other words,	"
say -v Kyoko "	それは終わる，いつかは．	"; say -v Karen "	it will come to end one of these days.	"
say -v Kyoko "	適切な資格が必要とされている，その職種に．	"; say -v Karen "	Proper qualifications are required for the position; 	"
say -v Kyoko "	コンピュータが使えることは絶対だ	"; say -v Karen "	computer literacy is a must.	"
say -v Kyoko "	同封してください，履歴書をこの封筒に，	"; say -v Karen "	Enclose you resure in this envelope	"
say -v Kyoko "	そしてそれを提出しなさい，人事部に	"; say -v Karen "	and submit it to the personnel department.	"
say -v Kyoko "	君は楽観的だね，信じるなんて，	"; say -v Karen "	It's optimistic of you to believe that 	"
say -v Kyoko "	物事がうまくいくなんて．	"; say -v Karen "	things will work out. 	"
say -v Kyoko "	せいぜい50％の可能性がある	"; say -v Karen "	At best there's a fifty-fifty chance.	"
say -v Kyoko "	登録用紙は入手できる，無料で．	"; say -v Karen "	Registration forms can be obtained free of charge.	"
say -v Kyoko "	電話してください，今	"; say -v Karen "	Please give us a call now	"
say -v Kyoko "	あなたが参加したいなら，講習会に	"; say -v Karen "	if you want to participate in the workshop!	"
say -v Kyoko "	なお一層の問い合わせには，	"; say -v Karen "	For further inquiries,	"
say -v Kyoko "	遠慮なく連絡してください私たちに，フリーダイアルで	"; say -v Karen "	please feel free to contact us toll-free at 1-800-555-1212	"