#!/bin/bash

say -v Kyoko "	最近どう，ボブ？	"; say -v Karen "	How's it going, Bob? 	"
say -v Kyoko "	最高だよ．私はうまくいった，就職面接が．	"; say -v Karen "	Couldn't be better! I did well in my job interview. 	"
say -v Kyoko "	よくやった	"; say -v Karen "	Good for you.	"
say -v Kyoko "	彼は指示を与えた，研修生に，	"; say -v Karen "	He gave instructions to the trainees,	"
say -v Kyoko "	しかし彼らはさっぱりわからなかった，それらが	"; say -v Karen "	but they couldn't make heads of tails of them.	"
say -v Kyoko "	あなたは2つのことをできない，同時に．	"; say -v Karen "	You can't do two things at one time. 	"
say -v Kyoko "	それは無理だ．	"; say -v Karen "	It's out of question. 	"
say -v Kyoko "	それらを1つずつやりなさい	"; say -v Karen "	Do them one by one.	"
say -v Kyoko "	ボブ，邪魔するな，彼女の．	"; say -v Karen "	Bob, don't disturb her. 	"
say -v Kyoko "	おせっかいはやめろ．彼は囁いた	"; say -v Karen "	Mind your own business, he whispered.	"
say -v Kyoko "	もしあなたがしつこく困らせるなら，彼女を，そうやって，	"; say -v Karen "	If you persist in bothering her like that,	"
say -v Kyoko "	彼女は怒るだろう	"; say -v Karen "	she'll lose her temper.	"
say -v Kyoko "	彼はたいへん子供っぽいので彼は我慢できなかった，誘惑を	"; say -v Karen "	He was so childish that he couldn't resist temptation.	"
say -v Kyoko "	やめてください，騒ぐのは．	"; say -v Karen "	Stop making a fuss. 	"
say -v Kyoko "	それは本当にイライラする．彼女は叫んだ	"; say -v Karen "	It really gets on my nerves. She shouted.	"
say -v Kyoko "	無駄だ，ニックに口答えするのは．	"; say -v Karen "	There's no point in talking back to Nick. 	"
say -v Kyoko "	彼は独裁者だ，言ってみれば	"; say -v Karen "	He is a dictator, so to speak.	"
say -v Kyoko "	彼らはとても礼儀正しい，彼のいる前では．	"; say -v Karen "	They are very polite in his presence,	"
say -v Kyoko "	しかし実際には，	"; say -v Karen "	but actually,	"
say -v Kyoko "	彼らはいつも彼の陰口を言っている	"; say -v Karen "	they always talk about him behind his back.	"
say -v Kyoko "	あなたは軽蔑してるね，ニックを？	"; say -v Karen "	You despise Nick, don't you? 	"
say -v Kyoko "	それどころか．私は尊敬している，彼を	"; say -v Karen "	On the contrary! I look up to him.	"
say -v Kyoko "	彼の絶え間ない侮辱が呼び起こした，彼女の怒りを	"; say -v Karen "	His constant insults aroused her anger.	"
say -v Kyoko "	私はうんざりしている，書類の整理とかコーヒーを注ぐことに．	"; say -v Karen "	I'm fed up with just shuffling papers and pouring coffee. 	"
say -v Kyoko "	私は決心した，やめることを	"; say -v Karen "	I've made up my mind to quit.	"
say -v Kyoko "	現実には，	"; say -v Karen "	In reality,	"
say -v Kyoko "	多くの人々が苦労している，なんとかやりくりすることに．	"; say -v Karen "	many people have difficulty making ends meet. 	"
say -v Kyoko "	あなたはどうやって生活していけるか，10万で1ヶ月	"; say -v Karen "	How can you get by on 100,000 yen a month?	"
say -v Kyoko "	女性職員たちが不満を言うのも最もだ，	"; say -v Karen "	Female clerks may well complain 	"
say -v Kyoko "	彼女らの日常業務について，	"; say -v Karen "	about their routines,	"
say -v Kyoko "	それは全くやりがいがない	"; say -v Karen "	which are not challenging at all	"
say -v Kyoko "	抜本的な事業の再構築のおかげで，	"; say -v Karen "	Thanks to a fundamental restructuring, 	"
say -v Kyoko "	私たちの黒字は増大した，3倍に	"; say -v Karen "	our surplus has swelled threefold.	"
say -v Kyoko "	現在の多くの人々がみなしている，	"; say -v Karen "	Many people today think of 	"
say -v Kyoko "	会社への忠誠は馬鹿げた考えだと	"; say -v Karen "	loyalty to a company as an absurd notion.	"
say -v Kyoko "	私は通勤しなければならない，はるばる遠い郊外から．	"; say -v Karen "	I have to commute all the way from a distant suburb. 	"
say -v Kyoko "	私はうんざりだ，それには．	"; say -v Karen "	I'm sick of it	"