#!/bin/bash

say -v Kyoko "	私は気づいた，誰かが見つめているのを，私を，通路の向こうから．	"; say -v Karen "	I became aware of someone staring at me across the aisle,	"
say -v Kyoko "	なので私は振り向いた．しかし誰も見えなかった	"; say -v Karen "	so I turned around. But there was no one in sight.	"
say -v Kyoko "	彼女は悲鳴を上げた，恐怖で，	"; say -v Karen "	She screamed with horror	"
say -v Kyoko "	誰かが掴んだので，彼女の腕を．	"; say -v Karen "	as someone took hold of her arm.	"
say -v Kyoko "	彼女の安全が知らされて，	"; say -v Karen "	Informed of her safety,	"
say -v Kyoko "	彼はため息をついた，安堵の	"; say -v Karen "	he breathed a sigh of relief.	"
say -v Kyoko "	弾丸が貫通し，彼の胸を，	"; say -v Karen "	The bullet penetrated his chest,	"
say -v Kyoko "	彼を危険な状態にした	"; say -v Karen "	leaving him in critical condition.	"
say -v Kyoko "	現時点で，それはまだ不確かである，	"; say -v Karen "	At present, it's still uncertain	"
say -v Kyoko "	それが故意か過失なのかどうか	"; say -v Karen "	whether it was done deliberately or by accident.	"
say -v Kyoko "	デリカテッセンに火がついて全焼した，	"; say -v Karen "	A deli caught fire and burned down,	"
say -v Kyoko "	灰の山を残して	"; say -v Karen "	leaving a heap of ashes.	"
say -v Kyoko "	突然花火倉庫が爆発し，	"; say -v Karen "	All of a sudden the fireworks warehouse exploded,	"
say -v Kyoko "	2日かかった，消すのに激しい炎を	"; say -v Karen "	and it took two days to put out the blaze.	"
say -v Kyoko "	爆弾が爆発し，30階建てのビルで，	"; say -v Karen "	A bomb went off in a thirty-story building,	"
say -v Kyoko "	50人以上がひどく負傷した	"; say -v Karen "	and more than fifty people were seriouosly wounded.	"
say -v Kyoko "	貨物船，アテネに向かっている，は沈んだ，	"; say -v Karen "	A cargo vessel, bound for Athens, sank 	"
say -v Kyoko "	地中海で，なんの痕跡も残さずに	"; say -v Karen "	in the Mediterranean/without a trace.	"
say -v Kyoko "	無謀な男は凍死した，	"; say -v Karen "	The reckless men froze to death 	"
say -v Kyoko "	彼らの探検中に，南極の	"; say -v Karen "	during their expedition to the antarctic.	"
say -v Kyoko "	悲劇は覚えておかなければならない，	"; say -v Karen "	The tragedy must be remembered	"
say -v Kyoko "	繰り返さないように	"; say -v Karen "	so as not to be repeated.	"