#!/bin/bash

say -v Kyoko "	その巨大な記念碑は建てられた，	"; say -v Karen "	An immense monument was erected	"
say -v Kyoko "	敬意を表して，高潔な愛国者に	"; say -v Karen "	in honor of the noble patriot.	"
say -v Kyoko "	彼はひざまずいて祈りを捧げた	"; say -v Karen "	He got down on his knees	"
say -v Kyoko "	個人の霊に	"; say -v Karen "	and prayed for the souls of the deceised.	"
say -v Kyoko "	最高裁判所は位置する，皇居の近くに	"; say -v Karen "	The Supreme Court is located near the Imperial palace.	"
say -v Kyoko "	中絶賛成グループが抗議した	"; say -v Karen "	The pro-choice group protested against	"
say -v Kyoko "	禁止に対して，中絶の	"; say -v Karen "	a ban on abortion.	"
say -v Kyoko "	上院議員のフォードは中立のままでいた，	"; say -v Karen "	Senator Ford remained neutral	"
say -v Kyoko "	その激しい論争において	"; say -v Karen "	in the bitter controversy.	"
say -v Kyoko "	フォードは困難な立場にある，	"; say -v Karen "	Ford has been in a difficult situation	"
say -v Kyoko "	一週間ずっと．	"; say -v Karen "	all week long. 	"
say -v Kyoko "	彼はもはやできない，	"; say -v Karen "	He is no longer capable of	"
say -v Kyoko "	対処することが，それに	"; say -v Karen "	coping with it.	"
say -v Kyoko "	首脳会談は放送される予定だ，同時に，	"; say -v Karen "	The summit talks are to be broadcast simultaneously	"
say -v Kyoko "	世界中で	"; say -v Karen "	throughout the world	"
say -v Kyoko "	外交の対話が役立った，終止符を打つことに，その紛争の	"; say -v Karen "	Diplomatic dialogue helped put an end to the conflict.	"
say -v Kyoko "	ジョンソンは任命された，親善大使として，	"; say -v Karen "	Johnson was appointed as a goodwill ambassador	"
say -v Kyoko "	相互理解を育むために，両国の	"; say -v Karen "	to foster mutual understanding between the nations.	"
say -v Kyoko "	専門家は予測してる，	"; say -v Karen "	The specialist predicts	"
say -v Kyoko "	国際的な緊張が高まると	"; say -v Karen "	international tension will build up.	"
say -v Kyoko "	私の考えでは，	"; say -v Karen "	In my opinion,	"
say -v Kyoko "	永久の平和は幻想にすぎない	"; say -v Karen "	permanent peace is nothing but an illusion.	"
say -v Kyoko "	民族の少数派は戦っている，偏見，貧困と抑圧に	"; say -v Karen "	Ethnic minorities struggle against prejudice, poverty, and oppression.	"
say -v Kyoko "	私たちは努力しなければならない，	"; say -v Karen "	We must make every effort 	"
say -v Kyoko "	廃止するために，すべての差別を	"; say -v Karen "	to do away with all discrimination.	"
say -v Kyoko "	移民たちは耐えてきた，肉体的，精神的苦痛に	"; say -v Karen "	The immigrants have endured physical and mental pain.	"
say -v Kyoko "	その改正案は却下された，	"; say -v Karen "	The amendment was rejected	"
say -v Kyoko "	なぜならそれは人種の多様性を考慮に入れてなかったので，	"; say -v Karen "	because it didn't take racial diversity into account.	"
say -v Kyoko "	言うまでもなく，	"; say -v Karen "	Needless to say,	"
say -v Kyoko "	難民たちは切望していた，自由を	"; say -v Karen "	the refugees were longing for freedom.	"