#!/bin/bash

say -v Kyoko "	私は過ごしたい，残りの人生を	"; say -v Karen "	I want to spend the rest of my life	"
say -v Kyoko "	追求することに理想を	"; say -v Karen "	pursuing my ideals.	"
say -v Kyoko "	退職後，テレサは身を捧げた	"; say -v Karen "	After retirement, Teresa devoted herself	"
say -v Kyoko "	世話をすることに，孤児の	"; say -v Karen "	to caring for orphans.	"
say -v Kyoko "	困っている子どもたちのために，	"; say -v Karen "	For the sake of children in need, 	"
say -v Kyoko "	私たちは協力した，お金を集めることに	"; say -v Karen "	we cooperated to collect donations.	"
say -v Kyoko "	その慈善団体は名付けられている，	"; say -v Karen "	The charity is named after/	"
say -v Kyoko "	寄付した人の20億円	"; say -v Karen "	a man who gave away some two billion yen.	"
say -v Kyoko "	彼の自叙伝が発売され，今日，	"; say -v Karen "	His autobiography was released today	"
say -v Kyoko "	そして完売した，昼までに	"; say -v Karen "	and was sold out by noon.	"
say -v Kyoko "	テッドが，高潔な人だと呼ばれている	"; say -v Karen "	Ted, who is often referred to as a man of integrity,/	"
say -v Kyoko "	立候補する，市長に．	"; say -v Karen "	is going to run for mayor.	"
say -v Kyoko "	その候補者はがっかりした，	"; say -v Karen "	The candidate was disappointed	"
say -v Kyoko "	選挙の結果に	"; say -v Karen "	by the outcome of the election.	"
say -v Kyoko "	市議会は集中するべきだ、もっと具体的な問題に	"; say -v Karen "	The municipal council should concentrate more on specific issues.	"
say -v Kyoko "	事実である	"; say -v Karen "	It is the case that	"
say -v Kyoko "	年金生活者が強いられていることは，	"; say -v Karen "	those who live on a pension are forced	"
say -v Kyoko "	厳しい生活を	"; say -v Karen "	to lead a hard life.	"
say -v Kyoko "	私たちは除外するべきだ，このデータを．	"; say -v Karen "	We should leave out this data. 	"
say -v Kyoko "	それは程遠い，正確さから	"; say -v Karen "	It's far from accurate.	"