#!/bin/bash

say -v Kyoko "	その曖昧な噂はわかった，嘘だと．	"; say -v Karen "	The vague rumor proved to be false. 	"
say -v Kyoko "	それでもやはり，多少の疑いは残っている．	"; say -v Karen "	Nevertheless, some skepticism lingers on.	"
say -v Kyoko "	上級の役人が疑われている，	"; say -v Karen "	A senior official is suspected of	"
say -v Kyoko "	賄賂を受け取っていると，企業から．	"; say -v Karen "	accepting bribes from a company,	"
say -v Kyoko "	しかし十分な証拠はない，彼を逮捕するのに．	"; say -v Karen "	but there isn't sufficient evidence to arrest him.	"
say -v Kyoko "	ジェイソン，プロジェクトの担当者は	"; say -v Karen "	Jason, who was in charge of the project,	"
say -v Kyoko "	解雇された，汚職で．	"; say -v Karen "	was dismissed for corruption.	"
say -v Kyoko "	私の知る限りでは，	"; say -v Karen "	To my knowledge,	"
say -v Kyoko "	彼は彼は関わっていない，	"; say -v Karen "	he has not been involved	"
say -v Kyoko "	詐欺の企みには．	"; say -v Karen "	in the fraud scheme.	"
say -v Kyoko "	彼らは発見した，真実を	"; say -v Karen "	They found out the truth	"
say -v Kyoko "	調べている間，関連書類の山を．	"; say -v Karen "	while examining a pile of relevant documents.	"
say -v Kyoko "	審判の間，明るみに出た，	"; say -v Karen "	During the trial it came to light	"
say -v Kyoko "	彼らが隠していたことが，	"; say -v Karen "	that they had been covering up	"
say -v Kyoko "	違法取引を，数十年．	"; say -v Karen "	illegal transactions for decades.	"
say -v Kyoko "	探偵は書き取った，彼の証言を．	"; say -v Karen "	The detective took down his testimony	"
say -v Kyoko "	その場で一言一句違わずに	"; say -v Karen "	on the spot, word for word.	"
say -v Kyoko "	初めて人生で，	"; say -v Karen "	For the first time in my life,	"
say -v Kyoko "	私は感じた，良心の苦しみを，	"; say -v Karen "	I felt a pang of conscience,	"
say -v Kyoko "	しかし，逃れる方法はなかった．	"; say -v Karen "	but there was no other way out.	"
say -v Kyoko "	私は頭から離れない，鮮やかな悪夢が，	"; say -v Karen "	I'm still haunted by a vivid nightmare	"
say -v Kyoko "	昨夜見た	"; say -v Karen "	I had last night.	"
say -v Kyoko "	概して，	"; say -v Karen "	By and large,	"
say -v Kyoko "	記者はためらわない，侵害することを，個人のプライバシーを	"; say -v Karen "	reporters don't hesitate to intrude in one's privacy.	"
say -v Kyoko "	著者は改訂した，原稿を、何度も何度も	"; say -v Karen "	The author revised his manuscript over and over again.	"
say -v Kyoko "	彼は誰にも劣らない，	"; say -v Karen "	He is second to none	"
say -v Kyoko "	過ちを指摘することとなると，他人の	"; say -v Karen "	when it comes to finding fault with others.	"
say -v Kyoko "	概して，	"; say -v Karen "	On the whole,	"
say -v Kyoko "	エリートは敏感でない，批判に．	"; say -v Karen "	the elite are not sensitive to criticism.	"
say -v Kyoko "	タブロイド紙が明らかにした時，	"; say -v Karen "	When a tabloid revealed that	"
say -v Kyoko "	彼が麻薬中毒であることを，	"; say -v Karen "	he was a drug addict,	"
say -v Kyoko "	彼の評判はほとんど失墜した．	"; say -v Karen "	his reputation was all but ruined.	"
say -v Kyoko "	彼らはよく検討した，すべての面を，防衛計画の，	"; say -v Karen "	They considered every aspect of the defence program	"
say -v Kyoko "	そして指摘した，たくさんの欠陥を．	"; say -v Karen "	and pointed out numerous flaws.	"