#!/bin/bash

say -v Kyoko "	私たちは寛容な態度をとるつもりはない，	"; say -v Karen "	We will not tolerate	"
say -v Kyoko "	テロに関わる人に	"; say -v Karen "	anyone who engages in terrorism.	"
say -v Kyoko "	悪名高い反乱兵は最終的に捕らえられた，	"; say -v Karen "	The notorious rebel was ultimately captured	"
say -v Kyoko "	そして閉じ込められた，拘置所に	"; say -v Karen "	and confined to jail.	"
say -v Kyoko "	軍隊は素早く呼ばれた，	"; say -v Karen "	Troops were swiftedly called in	"
say -v Kyoko "	鎮圧するために，暴動を．	"; say -v Karen "	to put down the riot.	"
say -v Kyoko "	私たちは理性に訴えるべきだ，	"; say -v Karen "	We should appeal to reason	"
say -v Kyoko "	暴力という手段を取る代わりに，	"; say -v Karen "	instead of resorting to violence.	"
say -v Kyoko "	私は提案する，私たちは採用することを柔軟な戦術を．	"; say -v Karen "	I suggest we adopt flexible tactics	"
say -v Kyoko "	今のところは	"; say -v Karen "	for the moment.	"
say -v Kyoko "	全軍は成功した，	"; say -v Karen "	The armed forces succeeded in	"
say -v Kyoko "	占領することを，全ての領土を	"; say -v Karen "	occupying the entire territory.	"
say -v Kyoko "	このような状況下では，	"; say -v Karen "	Under the circumstances,	"
say -v Kyoko "	敵はせざるを得ない，降伏を．	"; say -v Karen "	the enemy has no choice but to surrender. 	"
say -v Kyoko "	彼らは持ちこたえられない，これ以上．	"; say -v Karen "	They can't hold out any longer.	"
say -v Kyoko "	遅かれ早かれ，	"; say -v Karen "	Sooner or later,	"
say -v Kyoko "	人質は開放されるだろう	"; say -v Karen "	the hostages will be set free.	"
say -v Kyoko "	支配のもとで，専制政治の，	"; say -v Karen "	Under the reign of tyranny,	"
say -v Kyoko "	無実の人々が剥奪された，市民権を．	"; say -v Karen "	innocent people were deprived of their citizenship.	"
say -v Kyoko "	幾つかの兵士が気が進まなかった，	"; say -v Karen "	Some soldiers were reluctant	"
say -v Kyoko "	従うことにその命令に．	"; say -v Karen "	to obey the commands.	"
say -v Kyoko "	彼の政権はきっと崩壊する．	"; say -v Karen "	His regime is bound to collapse.	"
say -v Kyoko "	その同盟国は激しく非難した，その侵略を，	"; say -v Karen "	The allies condemned the invasion	"
say -v Kyoko "	国連決議に違反するとして	"; say -v Karen "	as a violation of UN resolutions.	"
say -v Kyoko "	私たちは排除できない，その可能性を，	"; say -v Karen "	We cannot rule out the possibility	"
say -v Kyoko "	内乱が勃発するという，その国で．	"; say -v Karen "	that civil war will break out in that country.	"
say -v Kyoko "	その植民地は宣言した，独立を．	"; say -v Karen "	The colony declared independence	"
say -v Kyoko "	そして共和国になった．	"; say -v Karen "	and became a republic.	"