#!/bin/bash

say -v Kyoko "	警察は探している，手がかりを，	"; say -v Karen "	The cops are searching for clues	"
say -v Kyoko "	その残虐な殺人の	"; say -v Karen "	to the brutal murder.	"
say -v Kyoko "	その男は正気でないに違いない．	"; say -v Karen "	The man must be insane. 	"
say -v Kyoko "	彼は区別できない，悪いことと正しいことの	"; say -v Karen "	He can't distinguish vice from virtue.	"
say -v Kyoko "	指紋は，凶器に残っていた，	"; say -v Karen "	The fingerprints left on the weapon	"
say -v Kyoko "	一致した，容疑者のものと	"; say -v Karen "	correspond with  the suspect's.	"
say -v Kyoko "	それは私たちみんなを驚かせた，	"; say -v Karen "	It took us all by surprise	"
say -v Kyoko "	著名な心理学者が訴えられた時，誘拐で	"; say -v Karen "	when the noted psychologist was accused of kidnapping.	"
say -v Kyoko "	陪審団の有罪評決が引き起こした，	"; say -v Karen "	The jury's guilty verdict gave rise to	"
say -v Kyoko "	広範囲の論争を	"; say -v Karen "	widespread debate.	"
say -v Kyoko "	その男は慈悲を懇願した，	"; say -v Karen "	The man pleaded for mercy,	"
say -v Kyoko "	しかし，彼は判決がくだされた，	"; say -v Karen "	but he was sentenced	"
say -v Kyoko "	20年の服役が，彼の罪に対して	"; say -v Karen "	to twenty years in prison for his crime.	"
say -v Kyoko "	勤務中の警官は気づいた，	"; say -v Karen "	The officer on duty perceived	"
say -v Kyoko "	お年寄りが近づいてくるのを，彼の後ろに	"; say -v Karen "	an elderly man coming up/behind him.	"
say -v Kyoko "	彼はちらっと見かけた，	"; say -v Karen "	He caught sight of a thief	"
say -v Kyoko "	泥棒が不法侵入しようとしているのを，その家に	"; say -v Karen "	attempting to break into the house.	"
say -v Kyoko "	一昨日彼は目撃した，	"; say -v Karen "	The day before yesterday he witnessed 	"
say -v Kyoko "	奇妙な事件を，その原野で	"; say -v Karen "	a weird incident in the wilderness.	"