#!/bin/bash

say -v Kyoko "	私たちは連想する傾向がある，	"; say -v Karen "	We tend to associate	"
say -v Kyoko "	政治家から偽善を	"; say -v Karen "	politicians with hypocrisy.	"
say -v Kyoko "	彼らは第一に関心がある，搾取することに，私たちから，	"; say -v Karen "	They are primarily concerned with exploiting us,	"
say -v Kyoko "	高めることよりも，生活水準を	"; say -v Karen "	not with enhancing our living standards.	"
say -v Kyoko "	その男はかつて行使していた，	"; say -v Karen "	The man once exerted 	"
say -v Kyoko "	支配的な影響力を保守政党に対して，	"; say -v Karen "	a dominant influence on the conservative party,	"
say -v Kyoko "	しかし今は彼の力は弱まっている．	"; say -v Karen "	but now his power is diminishing.	"
say -v Kyoko "	報道担当者は断った，コメントすることを，言いながら，	"; say -v Karen "	The spokesperson refused to make any comment, saying,	"
say -v Kyoko "	それは調査中ですと	"; say -v Karen "	It's under investigation.	"
say -v Kyoko "	警察は言う，誰かが糸を引いていると，背後で	"; say -v Karen "	The police say there's someone pulling strings behind the scenes.	"
say -v Kyoko "	役員たちはもてなした，官僚を料亭で，	"; say -v Karen "	The executives entertained the bureaucrats at ryotei,	"
say -v Kyoko "	すなわち高級な日本料理店で．	"; say -v Karen "	or exclusive Japanese restaurant,	"
say -v Kyoko "	期待して何らかの見返りを．	"; say -v Karen "	hoping for something in return.	"
say -v Kyoko "	彼の秘書はきっぱりと否定した，	"; say -v Karen "	His secretary flatly denied	"
say -v Kyoko "	漏らしていることを機密情報を	"; say -v Karen "	leaking any confidential information.	"
say -v Kyoko "	誰も思い切って意見を否定しない，彼，彼女の雇用主を．	"; say -v Karen "	No one dares to contradict/his/her employer	"
say -v Kyoko "	恐れているので解雇を．	"; say -v Karen "	for fear of being fired.	"
say -v Kyoko "	彼は犠牲にした，彼の前途有望な経歴を	"; say -v Karen "	He sacrificed his promising career	"
say -v Kyoko "	尊厳を維持するために	"; say -v Karen "	to retain his dignity.	"
say -v Kyoko "	私は自殺したほうがマシだ，	"; say -v Karen "	I might as well kill myself	"
say -v Kyoko "	受け入れるくらいなら運命を	"; say -v Karen "	as reconcile myself to my fate.	"
say -v Kyoko "	彼は自殺するところだった，	"; say -v Karen "	He was about to commit suicide	"
say -v Kyoko "	毒物を飲み込んで．	"; say -v Karen "	by swallowing poison	"
say -v Kyoko "	彼は考え直した時	"; say -v Karen "	when he thought better of it.	"