#!/bin/bash

say -v Kyoko "	私は物を買いがちです、衝動的に	"; say -v Karen "	I'm apt to buy things on impulse  	"
say -v Kyoko "	いつでも何かが安売りをしているときに．	"; say -v Karen "	whenever something is on sale.	"
say -v Kyoko "	私もそうです	"; say -v Karen "	So am I.	"
say -v Kyoko "	実際のところ，	"; say -v Karen "	As it is, 	"
say -v Kyoko "	普通の人々には購入する余裕がない	"; say -v Karen "	ordinary people cannnot afford to purchase	"
say -v Kyoko "	そんな贅沢品を	"; say -v Karen "	such luxuries.	"
say -v Kyoko "	私達が予期していたように	"; say -v Karen "	As we anticipated, 	"
say -v Kyoko "	失業率は上昇した	"; say -v Karen "	the unemployment rate has risen	"
say -v Kyoko "	３四半期連続で	"; say -v Karen "	three quarters in a row.	"
say -v Kyoko "	私は減らさなければならない、出費を．	"; say -v Karen "	I have to cut down on my expenses,	"
say -v Kyoko "	だからこれからは	"; say -v Karen "	so from now on,	"
say -v Kyoko "	私はお金の流れを記録するつもりだ、いちにち単位で	"; say -v Karen "	I'm going to keep track of them on a daily basis.	"
say -v Kyoko "	いずれにせよ	"; say -v Karen "	In any case,	"
say -v Kyoko "	組合は妥協しなければならない、ある程度	"; say -v Karen "	the union has to compromise to a certain extent.	"
say -v Kyoko "	有能な整備士は需要がある	"; say -v Karen "	Competent mechanics are in great demand,	"
say -v Kyoko "	だから彼らは稼げる、かなり良い賃金を	"; say -v Karen "	so they earn decent wages.	"
say -v Kyoko "	大統領は具体的な計画を発表した	"; say -v Karen "	The president announced a concrete plan	"
say -v Kyoko "	福祉改革を実行するための	"; say -v Karen "	to carry out welfare reform.	"
say -v Kyoko "	彼の政策はきっと至るだろう．	"; say -v Karen "	His policy will no doubt lead  	"
say -v Kyoko "	暗い結果に	"; say -v Karen "	to dismal consequences.	"
say -v Kyoko "	それは必要とする、徹底的な見直しを	"; say -v Karen "	It needs a thorough review.	"
say -v Kyoko "	それは言うまでもない	"; say -v Karen "	It goes without saying	"
say -v Kyoko "	高齢化社会が避けられないことは	"; say -v Karen "	that the aging of society is inevitable.	"
say -v Kyoko "	ちょっと見てください、このひょうを．	"; say -v Karen "	Please take a look at this chart. 	"
say -v Kyoko "	それは示しています	"; say -v Karen "	It indicates	"
say -v Kyoko "	少年非行が増加していることを、深刻な割合で	"; say -v Karen "	that juvenile delinquency is on the increase at an alearming rate.	"
say -v Kyoko "	多くの商業地区では	"; say -v Karen "	In many business districts, 	"
say -v Kyoko "	たくさんの空き地がある	"; say -v Karen "	there are a lot of vacant lots	"
say -v Kyoko "	売りに出されている、数年間	"; say -v Karen "	which have been for sale for years.	"
say -v Kyoko "	人口密度が、大都市の	"; say -v Karen "	The population density in the metropolis 	"
say -v Kyoko "	徐々に低下している	"; say -v Karen "	is gradually decreasing.	"
say -v Kyoko "	ほぼ間違いなく	"; say -v Karen "	In all likelihood	"
say -v Kyoko "	出生率は下がり続ける	"; say -v Karen "	the birthrate will continue to decline	"
say -v Kyoko "	着実に数年、これから先	"; say -v Karen "	steadily for years to come.	"