#!/bin/bash

say -v Kyoko "	発電所は供給している	"; say -v Karen "	The power plant supplies	"
say -v Kyoko "	遠く離れた郡に、電気を	"; say -v Karen "	the remote county with electricity.	"
say -v Kyoko "	あなたは許されていません	"; say -v Karen "	You are not allowed 	"
say -v Kyoko "	この装置を操作することを、許可なく	"; say -v Karen "	to operate this device without permission.	"
say -v Kyoko "	実は	"; say -v Karen "	In fact,	"
say -v Kyoko "	住民たちはさらされてきた、放射能に	"; say -v Karen "	the inhabitants have been exposed to radiation.	"
say -v Kyoko "	いくら強調してもしすぎることはない	"; say -v Karen "	One cannot emphasize too much 	"
say -v Kyoko "	潜在的な危険性を、核エネルギーの	"; say -v Karen "	the potential danger of nuclear energy.	"
say -v Kyoko "	数年間	"; say -v Karen "	For years 	"
say -v Kyoko "	報道陣はその問題を見落としていた．	"; say -v Karen "	 the press overlooked the problem. 	"
say -v Kyoko "	しかし今、どちらかと言えば	"; say -v Karen "	But now, if anything,	"
say -v Kyoko "	彼らはそれを重視しすぎている	"; say -v Karen "	they are making too much of it.	"
say -v Kyoko "	穀物を栽培するだけでなく	"; say -v Karen "	As well as cultivating grain,	"
say -v Kyoko "	その農場経営者は食料雑貨店も経営している	"; say -v Karen "	the farmer runs a grocery store.	"
say -v Kyoko "	その研究所は設立された	"; say -v Karen "	The research institute was established	"
say -v Kyoko "	１９６０年代後半に	"; say -v Karen "	 in the late 1960s.	"
say -v Kyoko "	スターさんに相談したらどうですか、直接会って．	"; say -v Karen "	Why don't you consult Starr in person? 	"
say -v Kyoko "	彼は間違いなく最も著名な弁護士です	"; say -v Karen "	He's by far the most prominent attorney	"
say -v Kyoko "	このあたりでは	"; say -v Karen "	around here.	"
say -v Kyoko "	私はそれを書き留めます、念のため	"; say -v Karen "	I'll wrote it down just in case,	"
say -v Kyoko "	なぜなら私は記憶力が悪いから．	"; say -v Karen "	because I have bad memory.	"
say -v Kyoko "	弁護士は勧めた	"; say -v Karen "	The lawer recommended	"
say -v Kyoko "	彼の依頼人が法的手段を取ることを	"; say -v Karen "	that his client take legal action	"
say -v Kyoko "	保険会社に対して	"; say -v Karen "	against the insurance company.	"