#!/bin/bash

say -v Kyoko "	ジェニファーはだました，私を．	"; say -v Karen "	Jennifer deceived me. 	"
say -v Kyoko "	あなたは分別を持つべきだった，彼女を信じないくらいの	"; say -v Karen "	You should have known better than to trust her.	"
say -v Kyoko "	トムは後悔した，無駄にしてきたことを，人生の多くを	"; say -v Karen "	Tom regretted having wasted a great deal of his life.	"
say -v Kyoko "	私は思春期を振り返るときはいつも，憂鬱に感じる．	"; say -v Karen "	I cannot look back on my adolescence without feeling depressed.	"
say -v Kyoko "	ジェニファーは私を見捨てて他のところに行った．	"; say -v Karen "	Jennifer left me for another guy. 	"
say -v Kyoko "	えっ，それはつらい．	"; say -v Karen "	Oh, you must be upset. 	"
say -v Kyoko "	そうでもないよ．私は慣れている．	"; say -v Karen "	Not really. I'm used to it.	"
say -v Kyoko "	当然だ，彼女が見送りに来なかったのも．	"; say -v Karen "	No wonder she didn't show up to see him off. 	"
say -v Kyoko "	どうして？彼らは別れた．	"; say -v Karen "	How come? They broke up. 	"
say -v Kyoko "	それはかわいそうに	"; say -v Karen "	Oh, what a pity.	"
say -v Kyoko "	ここで生きていくこと，たった一人では拷問だ，	"; say -v Karen "	Living here all by myself is torture. 	"
say -v Kyoko "	彼はすすり泣きしていった．	"; say -v Karen "	He sobbed.	"
say -v Kyoko "	正直に言うと，私は熱狂的ファンである，ケンの．	"; say -v Karen "	To be honest, I'm crazy about Ken	"
say -v Kyoko "	なぜなら彼は勇敢で，自信があって，決して危険を犯すことを恐れない．	"; say -v Karen "	because he's brave, self-confident, and never afraid of taking risks. 	"
say -v Kyoko "	私だったらデートに誘う	"; say -v Karen "	If I were you, I'd ask him out.	"
say -v Kyoko "	私は付き合ったり別れたりしている，ジェニファーと，随分と長い間．	"; say -v Karen "	I've been going with Jennifer on and off for ages. 	"
say -v Kyoko "	あなたは相変わらず決断力がない．	"; say -v Karen "	You're as indecisive as ever. 	"
say -v Kyoko "	もう落ち着いていい頃だ	"; say -v Karen "	Isn't it about time you settled down?	"
say -v Kyoko "	気づいてきたよ，私がジェニファーに騙されていたことに，最初からずっと．	"; say -v Karen "	It dawned on me that/I had been taken in by Jennifer all along. 	"
say -v Kyoko "	なんてうぶなんだ．あなたは彼女の正体が見抜けなかったのか？	"; say -v Karen "	How naïve. Didn't you see through her?	"
say -v Kyoko "	実際に彼女は誰かと付き合っているけれども，	"; say -v Karen "	Even though she is seeing someone else,	"
say -v Kyoko "	私は諦めない	"; say -v Karen "	I won't give her up.	"
say -v Kyoko "	やあジェーン，どうだい調子は？別に．あなたは？	"; say -v Karen "	Hi Jane. What's up? Not much. How about you? 	"
say -v Kyoko "	結婚したよ，ジェニファーと．ええ，おめでとう．	"; say -v Karen "	I got married to Jennifer. Wow. Congratulations.	"
say -v Kyoko "	あなたが大変なときや気分が落ち込んでるときはいつでも，	"; say -v Karen "	Whenever you're in trouble or feeling down,	"
say -v Kyoko "	私はそばにいる	"; say -v Karen "	I'll be there for you.	"
say -v Kyoko "	喜びは反対です，悲しみの	"; say -v Karen "	Delight is the opposite of sorrow.	"
say -v Kyoko "	ジェニファーは僕を馬鹿呼ばわりさえもする，	"; say -v Karen "	Jennifer went so far as to call me an idiot	"
say -v Kyoko "	そして彼女はそれを撤回しない．	"; say -v Karen "	and she wouldn't take it back. 	"
say -v Kyoko "	当然の報いだ，あなたが挑発したんでしょう？	"; say -v Karen "	Serves you right. You provoked her, didn't you?	"
say -v Kyoko "	どうして我慢するの，彼女の傲慢さを．	"; say -v Karen "	Why do you put up with her arrogance? 	"
say -v Kyoko "	彼女は利用しているだけだ，あなたを．黙れ	"; say -v Karen "	She's just taking advantage of you. Shut up.	"
say -v Kyoko "	あわてないで．わたしはわかる，	"; say -v Karen "	Take your time. I know 	"
say -v Kyoko "	あなたは必要だ,2,3日，それを考えるのに	"; say -v Karen "	you need a couple of days to reflect on it. 	"
say -v Kyoko "	ボブは乗り切らなければならなかった，この厳しい試練を，彼自身で	"; say -v Karen "	Bob has to get through this ordeal on his own.	"