#!/bin/bash

say -v Kyoko "	展覧会は提供する，深い洞察を，	"; say -v Karen "	The exhibition offers profound insights	"
say -v Kyoko "	古代文明の	"; say -v Karen "	into ancient civilization.	"
say -v Kyoko "	ジョットは認められている，種をまいたことでイタリア・ルネサンスの	"; say -v Karen "	Giotto is credited with sowing the seeds/of the Italian Renaissance.	"
say -v Kyoko "	ボブははめ込んだ，肖像画を装飾された額に，	"; say -v Karen "	Bob mounted the portrait in a fancy frame,	"
say -v Kyoko "	しかし，それは上下逆さまだった	"; say -v Karen "	but it was upside down.	"
say -v Kyoko "	この荘厳な大聖堂は遡る，中世まで．	"; say -v Karen "	The magnificent cathedral dates back to the Middle Ages.	"
say -v Kyoko "	アジアの宗教は彼にひらめきを与え，創造した，	"; say -v Karen "	Asian religions inspired him to create 	"
say -v Kyoko "	素晴らしい彫刻作品を	"; say -v Karen "	splendid sculptures.	"
say -v Kyoko "	彼らは探検した，砂漠を，	"; say -v Karen "	They explored the desert	"
say -v Kyoko "	埋められた財宝を求めて	"; say -v Karen "	in search of buried treasure.	"
say -v Kyoko "	大富豪は主張した，獲得することを．その傑作を，	"; say -v Karen "	The millionaire insisted on acquiring the masterpiece	"
say -v Kyoko "	たとえどんなにコストがかかろうとも	"; say -v Karen "	no matter how much it cost.	"
say -v Kyoko "	神話と伝説は伝えられるべきだ，代々	"; say -v Karen "	Myths and legends should be handed down from generation to generation.	"
say -v Kyoko "	その言語学者は流暢に話す，いくつかの中国の方言を	"; say -v Karen "	The linguist is fluent in several Chinese dialects.	"
say -v Kyoko "	その部族は崇拝した，先祖を．	"; say -v Karen "	The tribe worships its ancestors	"
say -v Kyoko "	そして独自の言葉を話した，私たちに知られていない	"; say -v Karen "	and speaks its own language, which is not familiar to us.	"
say -v Kyoko "	その文化人類学者は言う，	"; say -v Karen "	The anthropologist says 	"
say -v Kyoko "	古い慣習はまだよく見られる，その州で	"; say -v Karen "	old customs still prevail in the province.	"
say -v Kyoko "	意地の悪い魔女が邪悪な呪文をかけた，その男に．	"; say -v Karen "	The wicked witch cast an evil spell on the man	"
say -v Kyoko "	そして彼を虫に変えた	"; say -v Karen "	and turned him into a bug.	"
say -v Kyoko "	彼らは前進した，その険しい小道を通って．，	"; say -v Karen "	They proceeded along the steep path,	"
say -v Kyoko "	それは唯一の到着する方法だった，国境に	"; say -v Karen "	which was the sole access to the border.	"
say -v Kyoko "	大きな猿が現れた時，洞窟から，	"; say -v Karen "	When a big ape emerged from the cave,	"
say -v Kyoko "	彼らはビックリして逃げた	"; say -v Karen "	they got frightened and ran away.	"
say -v Kyoko "	信じてもらえないかもしれないが，	"; say -v Karen "	Believe it or not,	"
say -v Kyoko "	私は宇宙人を見てそれからそれは消えた．	"; say -v Karen "	I saw an alien and then it vanished. 	"
say -v Kyoko "	冗談はよしてくれ．	"; say -v Karen "	Give me a break.	"