#!/bin/bash

say -v Kyoko "	ちょっと時間を割いてくれませんか？	"; say -v Karen "	Can you spare a minute? 	"
say -v Kyoko "	私は話し合いたい，大事なことを，二人にとって	"; say -v Karen "	I'd like to discuss something of importance/to both of us.	"
say -v Kyoko "	些細なことに思えるかもしれないが，あなたには，	"; say -v Karen "	It may seem trivial to you	"
say -v Kyoko "	しかし私にとって，それは価値がある注意するだけの	"; say -v Karen "	but for me it's worth paying attention to.	"
say -v Kyoko "	ボブに関しては，なんでも受け入れる．	"; say -v Karen "	As for Bob is concerned, anything goes. 	"
say -v Kyoko "	それとは対象に，ジェーンはとても用心深い	"; say -v Karen "	By contrast, Jane is very cautious.	"
say -v Kyoko "	気まずい間のあとで	"; say -v Karen "	After an awkward pause,	"
say -v Kyoko "	ビルは彼女の手を取って連れて行った無理やり上の階に	"; say -v Karen "	Bill took her by the hand and dragged her upstairs.	"
say -v Kyoko "	ビルは慰めたかっただけだった，モニカを，	"; say -v Karen "	Bill just wanted to comfort Monica,	"
say -v Kyoko "	しかし彼女は解釈した，それを恋愛の興味だと．	"; say -v Karen "	but she interpreted it as romantic interest.	"
say -v Kyoko "	確かめたあと，彼女が深く眠っていることを，	"; say -v Karen "	After making sure she was sound asleep,	"
say -v Kyoko "	彼は静かに部屋を出て出発した	"; say -v Karen "	he crept out of the room and set off.	"
say -v Kyoko "	ここだけの話だけど，リサ，私は偶然見た，	"; say -v Karen "	Between you and me, Lisa,	"
say -v Kyoko "	ニックが情熱的に抱きしめているのを，女性を	"; say -v Karen "	I came across Nick passionately embracing a woman.	"
say -v Kyoko "	そのような発言は受けやすい，誤解を	"; say -v Karen "	Such a remark is open to misunderstanding.	"
say -v Kyoko "	私は我慢できない，もうこれ以上．	"; say -v Karen "	I can't stand it anymore. 	"
say -v Kyoko "	落ち着いて．私はそこに行くだろうできるだけ早く	"; say -v Karen "	Calm down. I'll come over as soon as possible.	"
say -v Kyoko "	文字通り受け取らないでください．	"; say -v Karen "	Don't take it literally. 	"
say -v Kyoko "	彼は傾向がある，大げさにいう．	"; say -v Karen "	He is inclined to exaggerate.	"
say -v Kyoko "	あなたは謝罪するべきだ，リサに，	"; say -v Karen "	You should apologize to Lisa	"
say -v Kyoko "	バカにしたことを．	"; say -v Karen "	for making fun of her. 	"
say -v Kyoko "	あなたは度を越した，今回．	"; say -v Karen "	You went too far this time. 	"
say -v Kyoko "	ああ，そうする，そのうち彼女の機嫌が良いときに．	"; say -v Karen "	Yeah… I will, sometime when she's in a better mood.	"
say -v Kyoko "	リサ，上手くやっている，ニックと？	"; say -v Karen "	Lisa, are you getting alnog with Nick? 	"
say -v Kyoko "	時々私は離婚しようかと考える，彼と．	"; say -v Karen "	Once in a while, I think of divorcing him. 	"
say -v Kyoko "	冗談でしょう	"; say -v Karen "	You must be kidding.	"
say -v Kyoko "	泣きながら，	"; say -v Karen "	In tears,	"
say -v Kyoko "	彼女は引き裂いた，彼の手紙を，そして投げ捨てた．	"; say -v Karen "	she tore up his letter and threw it away.	"