#!/bin/bash

say -v Kyoko "	彼は上手ではない，友達をつくるのが．	"; say -v Karen "	He is not good at making friends	"
say -v Kyoko "	そして，いつも自分の殻に閉じこもる	"; say -v Karen "	and always keeps to himself.	"
say -v Kyoko "	見つけられなかったので，彼が受け入れられる場所を，	"; say -v Karen "	Having found no place he felt he belonged,	"
say -v Kyoko "	彼は極度に不安で孤独だった	"; say -v Karen "	he was extremely uneasy and lonely.	"
say -v Kyoko "	私はかなり大変なことだとわかった，	"; say -v Karen "	I found it pretty hard to adjust	"
say -v Kyoko "	順応するのが，新しい環境に	"; say -v Karen "	to my new surroundings.	"
say -v Kyoko "	私は全く場違いだと感じた，	"; say -v Karen "	I felt utterly out of place	"
say -v Kyoko "	あの洗練された人たちの中で	"; say -v Karen "	among those sophisticated people.	"
say -v Kyoko "	実を言うと，私は好きではない，クラシック音楽が．	"; say -v Karen "	To tell the truth, I don't like classical music. 	"
say -v Kyoko "	しかし一方では，モリーは本当にはまっている	"; say -v Karen "	On the other hand, Molly is really into it.	"
say -v Kyoko "	ボブは引き出す，楽しみを，虫の観察から	"; say -v Karen "	Bob derives pleasure from observing insects.	"
say -v Kyoko "	いかがですか，トランプか何かは，気分転換に．	"; say -v Karen "	How about playing cards or something/for a change? 	"
say -v Kyoko "	悪いけど，そういう気分じゃないよ	"; say -v Karen "	Sorry, I'm not up for it.	"
say -v Kyoko "	お先にどうぞ．いやあなたがどうぞ．ありがとう．どういたしまして．	"; say -v Karen "	After you. No please, you go ahead. Thanks. You're welcome.	"
say -v Kyoko "	彼の姪は社交的で大人だ，年の割に．	"; say -v Karen "	His niece is sociable and mature for her age. 	"
say -v Kyoko "	彼女は通用する，20代で	"; say -v Karen "	She could pass for twenty-something.	"
say -v Kyoko "	じゃあね，よろしく家族に．ああ，またね．	"; say -v Karen "	Take care of yourself and say hi to your family for me. I will. See you later.	"
say -v Kyoko "	私は楽しみにしている，連絡をもらうのを，あなたから．こころから．	"; say -v Karen "	I'm looking forward to hearing from you. Sincerely.,	"