#!/bin/bash

say -v Kyoko "	かなり多くの人々が招待されている，	"; say -v Karen "	Quite a few people have been invited	"
say -v Kyoko "	祝うために，その夫婦の記念日を	"; say -v Karen "	to celebrate the couple's anniversary.	"
say -v Kyoko "	すべて準備ができるまでもうすぐだ．	"; say -v Karen "	It won't be long before everything is ready. 	"
say -v Kyoko "	その間に，ご自由にどうぞ，軽食を	"; say -v Karen "	In the meantime, help yourself to some snacks.	"
say -v Kyoko "	けばけばしくて奇妙な服を着ていたので，	"; say -v Karen "	Dressed in a loud and peculiar outfit,	"
say -v Kyoko "	彼女は目立った，人混みで	"; say -v Karen "	she stood out in the crowd.	"
say -v Kyoko "	すべての人は感動した，彼女のおもてなしに	"; say -v Karen "	All the guests were touched by her hospitality.	"
say -v Kyoko "	彼女のボロボロの服はふさわしくなかった，その場に	"; say -v Karen "	Her shabby clothes were not suitable for the occasion.	"
say -v Kyoko "	その話題は共有するには私的過ぎる，	"; say -v Karen "	That topic is too intimate to share with	"
say -v Kyoko "	偶然知り合った人と	"; say -v Karen "	casual acquaintances.	"
say -v Kyoko "	トムが酔っ払う時，彼は下品になって不快にさせる．	"; say -v Karen "	When Tom gets drunk, he gets crude and offensive. 	"
say -v Kyoko "	近づかないように，彼に．	"; say -v Karen "	Stay away from him.	"
say -v Kyoko "	彼はほとんど理解できない，	"; say -v Karen "	He could hardly comprehend	"
say -v Kyoko "	彼女がほのめかしていたことを	"; say -v Karen "	what she was implying.	"
say -v Kyoko "	ボブは恥ずかしかった，	"; say -v Karen "	Bob felt embarrassed	"
say -v Kyoko "	彼がからかわれたとき，女の子の前で	"; say -v Karen "	when he was teased in front of some girls.	"
say -v Kyoko "	彼の曖昧な返事は彼女をなおさらイライラさせた．	"; say -v Karen "	His ambiguous reply made her all the more irritated.	"
say -v Kyoko "	ボブはとても臆病で，赤面する，	"; say -v Karen "	Bob is very timid and blushes	"
say -v Kyoko "	女子とおしゃべりする時	"; say -v Karen "	when chatting with girls.	"
say -v Kyoko "	ニックは見下す，誰でも出身なら，地方の	"; say -v Karen "	Nick looks down on anyone who comes from a rural area.	"
say -v Kyoko "	どうしたのボブ？あなたはとても惨めに見える．	"; say -v Karen "	What's the matter, Bob? You look so miserable. 	"
say -v Kyoko "	ほっといてくれ．あなたには関係ないことだ	"; say -v Karen "	Leave me alone. It's none of your business.	"
say -v Kyoko "	ボブは変装していたけれども，	"; say -v Karen "	Although Bob was in disguise,	"
say -v Kyoko "	私は彼だとわかった，ひと目見て	"; say -v Karen "	I recognized him at a glance.	"
say -v Kyoko "	何をくすくす笑ってるんだ？	"; say -v Karen "	What are you chuckling about? 	"
say -v Kyoko "	ボブ，トレーナーが後ろ前だ．あっ．	"; say -v Karen "	Bob, you have your sweatshirt on backwards. Oops	"