#!/bin/bash

say -v Kyoko "	ハエと蚊が邪魔をした，彼の瞑想の	"; say -v Karen "	Flies and mosquitoes interfered with his meditation.	"
say -v Kyoko "	その神聖な儀式が行われた，	"; say -v Karen "	The sacred ritual took place 	"
say -v Kyoko "	2度の延期のあとで	"; say -v Karen "	after being postponed twice.	"
say -v Kyoko "	突然，お坊さんが笑いだし，	"; say -v Karen "	All at once, the Buddhist priest burst into laughter,	"
say -v Kyoko "	台無しにした，厳粛な雰囲気を	"; say -v Karen "	spoiling the solemn atmosphere.	"
say -v Kyoko "	口を手で隠しなさい，あなたが席，くしゃみ，あくびをするときは	"; say -v Karen "	Cover your mouth when you cough, sneeze, or yawn.	"
say -v Kyoko "	彼女の親戚の一人がなくなった，3日前に．	"; say -v Karen "	One of her relatives passed away three days ago. 	"
say -v Kyoko "	えっ，それは大変だね．お気の毒に．	"; say -v Karen "	Oh, that's too bad. I'm so sorry.	"
say -v Kyoko "	葬儀に参加することに加えて，	"; say -v Karen "	Besides attending the funeral,	"
say -v Kyoko "	彼女は必要があった，すべての段取りを付ける	"; say -v Karen "	she needs to make all the arrangements.	"
say -v Kyoko "	私はあなたの気持ちがわかる，ジェーン．悲しみはすぐに消えない．	"; say -v Karen "	I feel for you, Jane. Grief doesn't fade away quickly. 	"
say -v Kyoko "	大丈夫，私は克服するでしょう	"; say -v Karen "	I'm OK. I'll get over it.	"
say -v Kyoko "	彼女は大切にしている，貴重な思い出を，子供時代の	"; say -v Karen "	She cherishes the precious memories of her childhood.	"
say -v Kyoko "	ジェニファーといえば，彼女は婚約した，実業家と．	"; say -v Karen "	Speaking of Jennifer, she got engaged to a businessman. 	"
say -v Kyoko "	呆れて物が言えないわ．	"; say -v Karen "	I'm at a loss for words. 	"
say -v Kyoko "	私は願う，彼女が破局しないことを	"; say -v Karen "	I hope she won't break it off.	"
say -v Kyoko "	近頃は，結婚の動機は必ずしも純粋ではない．	"; say -v Karen "	These days, the motives for marriage are not necessarily pure. 	"
say -v Kyoko "	例えばジェニファーを見てご覧	"; say -v Karen "	Take Jennifer for example.	"
say -v Kyoko "	優しく接してくれ，ボブに．	"; say -v Karen "	Go easy on Bob. 	"
say -v Kyoko "	ほら，彼は経験している，つらい期間を，最近	"; say -v Karen "	You know, he's been going through a rough period recently.	"
say -v Kyoko "	ところで，今何時？	"; say -v Karen "	By the way, do you have the time? 	"
say -v Kyoko "	えーっと，8字15分前だ	"; say -v Karen "	Let's see … it's a quarter to eight.	"
say -v Kyoko "	今日はこのへんまでにしておこう，ボブ．	"; say -v Karen "	Let's call it a day, Bob. 	"
say -v Kyoko "	私はお腹がペコペコだ．ああ，おごるよ，晩飯を．	"; say -v Karen "	I'm starved. Yep. I'll buy you dinner.	"