#!/bin/bash

say -v Kyoko "	彼らは補償を受ける権利がある	"; say -v Karen "	They are entitled to be compensated	"
say -v Kyoko "	怪我に対する	"; say -v Karen "	for their injury.	"
say -v Kyoko "	現在までに	"; say -v Karen "	So far, 	"
say -v Kyoko "	２００人もの多くの人が亡くなった	"; say -v Karen "	no less than 200 people have died	"
say -v Kyoko "	インフルエンザの流行で	"; say -v Karen "	of the flu epidemic.	"
say -v Kyoko "	効果は、それらの錠剤の	"; say -v Karen "	The effect of those pills,	"
say -v Kyoko "	強烈だが短時間だ	"; say -v Karen "	is intense but brief.	"
say -v Kyoko "	彼は癖を持っている	"; say -v Karen "	He has a habit  	"
say -v Kyoko "	爪を噛む．	"; say -v Karen "	of biting his nails.	"
say -v Kyoko "	それは全くゾットする	"; say -v Karen "	It's absolutely disgusting.	"
say -v Kyoko "	私のおばあちゃんは腰を痛めた	"; say -v Karen "	My grandma strained her back 	"
say -v Kyoko "	彼女がかがんだときに	"; say -v Karen "	when she bent down	"
say -v Kyoko "	私の息子を抱こうとして	"; say -v Karen "	to hug my son.	"
say -v Kyoko "	もしあなたは肩がこっているなら	"; say -v Karen "	If you have a stiff neck,	"
say -v Kyoko "	試しなさい、薬草治療を	"; say -v Karen "	try an herbal remedy.	"
say -v Kyoko "	医学の飛躍的発展はもたらした	"; say -v Karen "	Medical breakthroughs have brought 	"
say -v Kyoko "	多大な恩恵を	"; say -v Karen "	about great benefits	"
say -v Kyoko "	人類全体に	"; say -v Karen "	for humanity as a whole.	"
say -v Kyoko "	私たちは適用できない、クローン技術を、牛に	"; say -v Karen "	We can't apply cloning techniques to cattle, 	"
say -v Kyoko "	なおさら人間には（適用してはいけない）．	"; say -v Karen "	let alone human beings.	"
say -v Kyoko "	それは禁止されている	"; say -v Karen "	It's forbidden.	"
say -v Kyoko "	クジラは分類される、哺乳類に	"; say -v Karen "	Whales are classified as mammals.	"
say -v Kyoko "	進化論は超えている	"; say -v Karen "	The theory of evolution is beyond 	"
say -v Kyoko "	私の想像力の範囲を	"; say -v Karen "	the reach of my imagination.	"
say -v Kyoko "	その生物学者は誇りを持っている	"; say -v Karen "	The biologist is proud of	"
say -v Kyoko "	自分の歴史的な発見に	"; say -v Karen "	his historical discovery	"
say -v Kyoko "	そして気にすることなく自慢げに話す、それについて	"; say -v Karen "	and doesn't mind boasting about it.	"
say -v Kyoko "	倫理上の理由で	"; say -v Karen "	On ethical grounds, 	"
say -v Kyoko "	彼らは反対している	"; say -v Karen "	they are opposed to	"
say -v Kyoko "	いわゆる遺伝子治療に	"; say -v Karen "	so-called gene therapy.	"
say -v Kyoko "	初期症状は、その病気の	"; say -v Karen "	The initial symptoms of the disease	"
say -v Kyoko "	高熱と喉の痛みです	"; say -v Karen "	are fever and a sore throat.	"
say -v Kyoko "	脳の構造は複雑です	"; say -v Karen "	The structure of the brain is complex.	"
say -v Kyoko "	病気のため	"; say -v Karen "	Owing to illness, 	"
say -v Kyoko "	何人かの代表者が欠席した	"; say -v Karen "	some representatives were absent	"
say -v Kyoko "	年次会議を	"; say -v Karen "	from the annual conference.	"
say -v Kyoko "	徐々に	"; say -v Karen "	Little by little,  	"
say -v Kyoko "	私の娘婿は回復している、胃がんから	"; say -v Karen "	my son-in-law is recovering from stomach cancer,	"
say -v Kyoko "	そして今は彼は元気だ	"; say -v Karen "	and now he is in good spirits.	"
say -v Kyoko "	これは偽物ですね？	"; say -v Karen "	This is fake, isn't it?  	"
say -v Kyoko "	それは本物の骨董品です．	"; say -v Karen "	Hey, it's a genuine antique.	"
say -v Kyoko "	まさか	"; say -v Karen "	No way.	"