#!/bin/bash

say -v Kyoko "	ほかに何か？	"; say -v Karen "	Anything else?  	"
say -v Kyoko "	以上です．	"; say -v Karen "	That's it. 	"
say -v Kyoko "	こちらでお召し上がりですか？	"; say -v Karen "	For here or to go?	"
say -v Kyoko "	持ち帰りで	"; say -v Karen "	To go.	"
say -v Kyoko "	いくらですかこの敷物は？	"; say -v Karen "	How much is this rug?  	"
say -v Kyoko "	１００ドル税込みで．	"; say -v Karen "	$100 including tax.	"
say -v Kyoko "	じゃあこれにします	"; say -v Karen "	OK, I'll take it.	"
say -v Kyoko "	私は思いません	"; say -v Karen "	I don't think 	"
say -v Kyoko "	そのパンツがあなたに似合うとは．	"; say -v Karen "	those pants look good on you. 	"
say -v Kyoko "	こっちを試して．	"; say -v Karen "	Try these on. 	"
say -v Kyoko "	それらは本当に流行っているよ	"; say -v Karen "	They're really in now!	"
say -v Kyoko "	彼はタクシーを降りた、急いで、言いながら	"; say -v Karen "	He got out of the cab in haste, saying, 	"
say -v Kyoko "	お釣りはいりません	"; say -v Karen "	Keep the change.	"
say -v Kyoko "	配達サービスは利用可能です	"; say -v Karen "	Delivery service is available 	"
say -v Kyoko "	当店のお客様は	"; say -v Karen "	to our customers 	"
say -v Kyoko "	僅かな追加料金で	"; say -v Karen "	for a slight extra charge.	"
say -v Kyoko "	私のおごりです．	"; say -v Karen "	It's on me. 	"
say -v Kyoko "	ダメ．あなたはごちそうする、毎回	"; say -v Karen "	No. You treat me every time	"
say -v Kyoko "	私達が外食するときは．	"; say -v Karen "	we eat out.	"
say -v Kyoko "	うーんわかった．割り勘にしよう	"; say -v Karen "	Well, okay. Let's sprit the check then.	"
say -v Kyoko "	私がブラブラしている間、ショッピングセンターを	"; say -v Karen "	While I was hanging out at the mall,	"
say -v Kyoko "	私は偶然出会った、ケンに	"; say -v Karen "	I ran into Ken.	"
say -v Kyoko "	私は現金が不足していた	"; say -v Karen "	I was short of cash, 	"
say -v Kyoko "	ので，私は１００ドルを引き出した	"; say -v Karen "	so I withdrew the $100	"
say -v Kyoko "	私が銀行口座に預金した、先週	"; say -v Karen "	that I had deposited in my bank account last week.	"
say -v Kyoko "	彼女の帰宅途中に	"; say -v Karen "	On her way home 	"
say -v Kyoko "	彼女は奪われた、ハンドバッグを	"; say -v Karen "	she was robbed of her purse.	"
say -v Kyoko "	それは変だ	"; say -v Karen "	That's odd.  	"
say -v Kyoko "	私に教えて、どのようにそれが起こったのか．	"; say -v Karen "	Tell me how it happened.	"
say -v Kyoko "	私は説明します、あなたに、あとで	"; say -v Karen "	I'll explain it to you later.	"
say -v Kyoko "	私の両親は与えた	"; say -v Karen "	My parents gave me 	"
say -v Kyoko "	６時の門限を、罰として	"; say -v Karen "	a 6 pm curfew as a punishment	"
say -v Kyoko "	なぜなら私が破ったので、約束を	"; say -v Karen "	because I broke my promise.	"
say -v Kyoko "	ことわざにある通り	"; say -v Karen "	As proverb goes,	"
say -v Kyoko "	目的は正当化する、手段を	"; say -v Karen "	The end justifies the means.	"
say -v Kyoko "	今や私はわかったので	"; say -v Karen "	Now that I've found	"
say -v Kyoko "	だれもいないことが、頼るための	"; say -v Karen "	that there's no one to turn to,	"
say -v Kyoko "	私はやっていくしかない、自分の力で	"; say -v Karen "	I'll have to stand on my own two feet.	"