#!/bin/bash

say -v Kyoko "	議長は私を遮って、言った	"; say -v Karen "	The chairman cut me off, saying,	"
say -v Kyoko "	話し合いを終わらせる時間です．	"; say -v Karen "	Time to wind things up. 	"
say -v Kyoko "	決を採りましょう	"; say -v Karen "	Let's take a vote.	"
say -v Kyoko "	私たちは率直な意見を交わした、会議で	"; say -v Karen "	We exchanged frank opinions in the meeting,	"
say -v Kyoko "	しかし，まとまった意見にはまだ到達していない	"; say -v Karen "	but consensus is yet to be reached	"
say -v Kyoko "	この件に関しては	"; say -v Karen "	regarding this matter.	"
say -v Kyoko "	あなたは賛成ですか，反対ですか、彼に．	"; say -v Karen "	Do you agree or disagree with him?	"
say -v Kyoko "	私は彼の味方です	"; say -v Karen "	 I'm on his side.	"
say -v Kyoko "	厳密に言えば	"; say -v Karen "	Strictly speaking,	"
say -v Kyoko "	彼の意見はいくらか異なっている/私のものとは	"; say -v Karen "	his view differs somewhat from mine.	"
say -v Kyoko "	詳しく説明していただけませんか、もう一度．	"; say -v Karen "	Could you go over it again? 	"
say -v Kyoko "	私は理解できませんでした	"; say -v Karen "	I couldn't make out	"
say -v Kyoko "	あなたが言おうとしていたことが	"; say -v Karen "	what you were getting at.	"
say -v Kyoko "	誰も私を支持してくれなかった、最初は	"; say -v Karen "	No one backed me at first,	"
say -v Kyoko "	しかし最終的には	"; say -v Karen "	but eventually	"
say -v Kyoko "	私はみんなを説得して、賛成してもらった、私の案に	"; say -v Karen "	I talked everyone into going along with my plan.	"
say -v Kyoko "	私は感心します、あなたの不屈の努力，勇気，そして知恵に．お世辞でも嬉しいよ	"; say -v Karen "	I admire your perseverance, courage and wisdom. You flatter me!	"
say -v Kyoko "	どうするかを決めるとき	"; say -v Karen "	In making a decision,	"
say -v Kyoko "	私は論理には頼らない、しかし本能を当てにする	"; say -v Karen "	I rely not on logic but on instinct.	"
say -v Kyoko "	彼は考え出した	"; say -v Karen "	He came up with 	"
say -v Kyoko "	独創的で賢明な解決策を	"; say -v Karen "	an ingenious, sensible solution	"
say -v Kyoko "	そして直ちにそれを実行に移した	"; say -v Karen "	and immediately put it into practice.	"
say -v Kyoko "	客観的な観点からすると	"; say -v Karen "	From an objective viewpoint,	"
say -v Kyoko "	前者は劣っている、後者よりも	"; say -v Karen "	the former is inferior  to the latter.	"
say -v Kyoko "	あなたの考えは素晴らしい、理論的には	"; say -v Karen "	Your idea sounds marvelous in theory,	"
say -v Kyoko "	しかし私は思わない、それが機能するとは、実際に	"; say -v Karen "	yet I don't think it will work in practice.	"
say -v Kyoko "	私達は彼に期待した、相手を打ち負かすことを	"; say -v Karen "	We expected him to defeat his opponent,	"
say -v Kyoko "	しかし彼は失敗した、私達の期待に応えることに	"; say -v Karen "	but he failed to live up to our expectations.	"
say -v Kyoko "	皮肉にも、彼らの最善の努力にも関わらず	"; say -v Karen "	Ironically, despite their best endeavors,	"
say -v Kyoko "	彼らの任務は結果に終わった	"; say -v Karen "	their mission resulted in	"
say -v Kyoko "	完全な失敗に	"; say -v Karen "	complete failure.	"
say -v Kyoko "	彼女の天賦の才能は埋め合わせた、彼女の不足を	"; say -v Karen "	Her genius makes up for her lack	"
say -v Kyoko "	直接得た経験の	"; say -v Karen "	of her firsthand experience.	"
say -v Kyoko "	彼女は素晴らしい能力を持っている	"; say -v Karen "	She possesses a great capacity	"
say -v Kyoko "	克服する、どんな障害も	"; say -v Karen "	 for overcoming any obstacle.	"
say -v Kyoko "	あなたの強固な支援がなかったら	"; say -v Karen "	Without your solid support,	"
say -v Kyoko "	その取引は上手く行かなかっただろう．	"; say -v Karen "	the deal would have fallen through.	"
say -v Kyoko "	あなたに感謝しています	"; say -v Karen "	 I'm grateful to you.	"