#!/bin/bash

say -v Kyoko "	可燃物を持っていくことは、機内へ	"; say -v Karen "	Bringing flammable items into the cabin 	"
say -v Kyoko "	禁止されている	"; say -v Karen "	is prohibited.	"
say -v Kyoko "	私たちの便は、ウィーンへの	"; say -v Karen "	Our flight to Vienna	"
say -v Kyoko "	遅れが出た、ちょっとした事故が原因で	"; say -v Karen "	was delayed on account of a minor accident.	"
say -v Kyoko "	飛行機が爆発した/	"; say -v Karen "	The plane blew up	"
say -v Kyoko "	そして飛び込んだ、海に	"; say -v Karen "	and plunged into the ocean,	"
say -v Kyoko "	全員を殺した、乗っていた	"; say -v Karen "	killing all the people on board.	"
say -v Kyoko "	彼らは働いている、昼夜休むことなく	"; say -v Karen "	They are working around the clock 	"
say -v Kyoko "	調査して、墜落の原因を	"; say -v Karen "	 looking into the cause of the crash.	"
say -v Kyoko "	不運にも、殆どの乗客が生き残らなかった、その大惨事で	"; say -v Karen "	Unfortunately, few passengers survived the catastrophe.	"
say -v Kyoko "	航空専門家が分析した、統計を、詳細に	"; say -v Karen "	The aviation expert analyzed the statistics in detail.	"
say -v Kyoko "	全従業員を代表して	"; say -v Karen "	On behalf of all the staff,	"
say -v Kyoko "	私は表現したい、私たちの同情を、犠牲者に対して	"; say -v Karen "	I'd like to express our sympathy for the victims.	"
say -v Kyoko "	ある意味	"; say -v Karen "	In a sense,	"
say -v Kyoko "	彼は責任を負うべきだ、その惨事の	"; say -v Karen "	he is to blame for the disaster.	"
say -v Kyoko "	車両は検査される、欠陥を、３ヶ月毎に	"; say -v Karen "	The vehicles are inspected for defeats every three months.	"