#!/bin/bash

say -v Kyoko "	私は驚いた、見て	"; say -v Karen "	I was amazed to see	"
say -v Kyoko "	うちの光熱費がそんな額になっているのを	"; say -v Karen "	that our utility bills came to so much.	"
say -v Kyoko "	閉めなさい、水道の栓を．	"; say -v Karen "	Turn the faucet off! 	"
say -v Kyoko "	母が叫んだ、激怒して	"; say -v Karen "	Mom yelled in a rage.	"
say -v Kyoko "	蓋をしっかり閉めなさい、食べ物が腐らないように	"; say -v Karen "	Tighten the lid so the food doesn't go bad.	"
say -v Kyoko "	私はあなたのハサミを貸してもらえますか．	"; say -v Karen "	Can I borrow your scissors? 	"
say -v Kyoko "	もちろん．はいどうぞ	"; say -v Karen "	Sure, here you are.	"
say -v Kyoko "	あなたは透明な接着剤を使っても良いです、針と糸の代わりに	"; say -v Karen "	You can substitute some transparent glue for a needle and thread.	"
say -v Kyoko "	私は染めました、この織物を	"; say -v Karen "	I dyed this fabric 	"
say -v Kyoko "	そしてそれは縮みました	"; say -v Karen "	and it shrank.	"
say -v Kyoko "	私はこの革のジャケットを処分している	"; say -v Karen "	I'm getting rid of this leather jacket	"
say -v Kyoko "	なぜならそれは擦り切れているから、肘のところが	"; say -v Karen "	because it's worn out at the elbows.	"
say -v Kyoko "	小麦粉を加えなさい、その混ぜ合せたものに	"; say -v Karen "	Add some flour to the mixture	"
say -v Kyoko "	そしてそれをかき混ぜなさい、それにとろみが付くまで	"; say -v Karen "	and stir it until it becomes thick.	"
say -v Kyoko "	私達はどのように扱うべきか、残り物を．	"; say -v Karen "	What should we do with the leftovers? 	"
say -v Kyoko "	それらを保存しよう、冷蔵庫に、とりあえず．	"; say -v Karen "	Keep them in the fridge for now. 	"
say -v Kyoko "	私はそれらを温めます、レンジであとで	"; say -v Karen "	I'll heat them in the microwave later.	"
say -v Kyoko "	私はつぎ込むことができた、すべてのお金を、新しいパソコンに	"; say -v Karen "	I could have laid out all that money on a new PC,	"
say -v Kyoko "	しかし考え直して	"; say -v Karen "	but on second thought 	"
say -v Kyoko "	私はとっておくことに決めた、まさかのときのために	"; say -v Karen "	I decided to put some aside for a rainy day.	"
say -v Kyoko "	携帯電話はなった、ちょっとした必需品に	"; say -v Karen "	A cell phone has become something of a necessity,	"
say -v Kyoko "	そして私はそれなしではやっていけない	"; say -v Karen "	and I can't do without one.	"
say -v Kyoko "	私がゆったりと座ってくつろいだ途端に	"; say -v Karen "	No sooner had I sat back and relaxed 	"
say -v Kyoko "	妻は私に頼んだ、雑用を	"; say -v Karen "	than my wife asked me to do the chores.	"
say -v Kyoko "	彼女は赤ちゃんを寝かせた	"; say -v Karen "	She laid the baby down 	"
say -v Kyoko "	そして彼女は横になった、彼のそばで	"; say -v Karen "	and lay down beside him.	"